{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/ATLAS;AdventureWorksDW",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "ATLAS",
            "database": "AdventureWorksDW"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "ServiceAccount"
        }
      },
      {
        "type": "structured",
        "name": "File/C:\\Users\\Brett Powell\\SampleDataSources\\AdWorks Sales Plan xlsx",
        "connectionDetails": {
          "protocol": "file",
          "address": {
            "path": "C:\\Users\\Brett Powell\\SampleDataSources\\AdWorks Sales Plan.xlsx"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "ServiceAccount"
        }
      }
    ],
    "tables": [
      {
        "name": "Internet Sales",
        "description": "Online sales transactions to Adventure Works customers (not resellers).",
        "columns": [
          {
            "name": "Freight",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Freight",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyCustom\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Order Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Order Quantity",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Discount Amount",
            "dataType": "decimal",
            "isHidden": true,
            "isNullable": false,
            "sourceColumn": "Discount Amount",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyCustom\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Tax Amount",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Tax Amount",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Order Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Due Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Due Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Ship Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Ship Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Unit Price",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyGeneral\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Product Standard Cost",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Product Standard Cost",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyGeneral\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Product Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Currency Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Currency Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Currency Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Promotion Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Promotion Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Promotion Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Sales Territory Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Sales Territory Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Sales Territory Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Sales Order Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sales Order Number",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Sales Order Number"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Sales Order Line Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Sales Order Line Number",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Sales Order Line Number"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Internet Sales-c1ce912d-1c55-42f8-812f-488151a9c9ef",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=#\"Internet Sales\"",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Internet Sales Products Sold Count",
            "expression": "CALCULATE(DISTINCTCOUNT('Product'[Product Alternate Key]),'Internet Sales') ",
            "formatString": "#,0"
          },
          {
            "name": "Internet Sales Freight Cost",
            "expression": "SUM('Internet Sales'[Freight])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Order Quantity",
            "expression": "sum('Internet Sales'[Order Quantity]) ",
            "formatString": "#,0"
          },
          {
            "name": "Internet Gross Sales",
            "description": "The sum of unit price multiplied by order quantity.",
            "expression": "SUMX('Internet Sales','Internet Sales'[Order Quantity]*'Internet Sales'[Unit Price]) ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Discounts",
            "expression": "sum('Internet Sales'[Discount Amount]) "
          },
          {
            "name": "Internet Net Sales",
            "description": "Internet Gross Sales minus Internet Sales Discounts.",
            "expression": "[Internet Gross Sales] - [Internet Sales Discounts]  ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Margin %",
            "expression": "DIVIDE([Internet Net Sales]-[Internet Sales Product Cost],[Internet Net Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Sales Product Cost",
            "description": "The sum of product standard cost multiplied by order quantity.",
            "expression": "SUMX('Internet Sales','Internet Sales'[Order Quantity]* 'Internet Sales'[Product Standard Cost])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Gross Product Margin %",
            "description": "Internet Gross Product Margin divided by Internet Gross Sales.",
            "expression": "DIVIDE([Internet Gross Product Margin],[Internet Gross Sales]) ",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Sales Orders",
            "expression": "DISTINCTCOUNT('Internet Sales'[Sales order number]) ",
            "formatString": "#,0"
          },
          {
            "name": "Internet Sales France Customer Count",
            "expression": "CALCULATE([Internet Sales Customer Count],Customer[Customer Country] = \"France\") ",
            "formatString": "#,0"
          },
          {
            "name": "Current Month Internet Net Sales",
            "expression": [
              "",
              "VAR CurrentMonth = LOOKUPVALUE('Date'[Calendar Year Month Number],'Date'[Date],TODAY())",
              "RETURN",
              "CALCULATE([Internet Net Sales],FILTER(ALL('Date'),'Date'[Calendar Year Month Number] = CurrentMonth))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true
          },
          {
            "name": "Current Year Internet Sales Margin %",
            "expression": [
              "",
              "VAR CY = LOOKUPVALUE('Date'[Calendar Year],'Date'[Date],TODAY())",
              "RETURN",
              "CALCULATE([Internet Sales Margin %],'Date'[Calendar Year] = CY )"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "isHidden": true
          },
          {
            "name": "Current Year Internet Sales Customer Count",
            "expression": [
              "",
              "VAR CY = LOOKUPVALUE('Date'[Calendar Year],'Date'[Date],TODAY())",
              "RETURN",
              "CALCULATE([Internet Sales Customer Count],'Date'[Calendar Year] = CY )"
            ],
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Internet Sales Rows",
            "expression": "COUNTROWS('Internet Sales')",
            "formatString": "#,0"
          },
          {
            "name": "Internet Net Product Margin",
            "description": "Internet Net Sales minus Internet Sales Product Cost.",
            "expression": "[Internet Net Sales] - [Internet Sales Product Cost] ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Per Customer",
            "expression": "DIVIDE([Internet Net Sales],[Internet Sales Customer Count]) ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales New Customers",
            "expression": [
              "",
              "VAR Today = TODAY() VAR CurrentYear = YEAR(Today)",
              "VAR PriorCustomers = ",
              "SUMMARIZE(CALCULATETABLE('Internet Sales',FILTER(ALL('Date'),'Date'[Calendar Year] <= CurrentYear-1)),'Customer'[Customer Alternate Key])",
              "VAR CYCustomers =  SUMMARIZE(CALCULATETABLE('Internet Sales',FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year Status] = \"Current Calendar Year\" &&",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))),'Customer'[Customer Alternate Key])",
              "RETURN",
              "CALCULATE(DISTINCTCOUNT('Customer'[Customer Alternate Key]),EXCEPT(CYCustomers,PriorCustomers))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Count of Product Rows",
            "expression": "COUNTROWS('Product')",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Internet Net Sales (Due Date)",
            "expression": "CALCULATE([Internet Net Sales], USERELATIONSHIP('Internet Sales'[Due Date],'Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true
          },
          {
            "name": "Internet Net Sales (Ship Date)",
            "expression": "CALCULATE([Internet Net Sales],USERELATIONSHIP('Internet Sales'[Ship Date],'Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true
          },
          {
            "name": "Employee Rows",
            "expression": "COUNTROWS(Employee)",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Internet Cost of Sales",
            "description": "Internet Sales Product Cost plus Internet Sales Freight Cost.",
            "expression": "[Internet Sales Product Cost] + [Internet Sales Freight Cost] ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Net Product Margin %",
            "description": "Net Sales minus Product Cost",
            "expression": "DIVIDE([Internet Net Product Margin],[Internet Net Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Gross Product Margin",
            "description": "Internet Gross Sales minus Internet Sales Product Cost.",
            "expression": "[Internet Gross Sales] - [Internet Sales Product Cost]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Product Margin %",
            "description": "Internet Net Product Margin divided by Internet Net Sales.",
            "expression": "DIVIDE([Internet Net Product Margin],[Internet Net Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Gross Margin",
            "description": "Internet Gross Sales minus Internet Cost of Sales.",
            "expression": "[Internet Gross Sales] - [Internet Cost of Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Gross Margin %",
            "description": "Internet Gross Product Margin divided by Internet Gross Sales.",
            "expression": "DIVIDE([Internet Gross Margin],[Internet Gross Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Margin",
            "description": "Internet Net Sales minus Internet Cost of Sales.",
            "expression": "[Internet Net Sales] - [Internet Cost of Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Margin %",
            "description": "Internet Net Margin divided by Internet Net Sales.",
            "expression": "DIVIDE([Internet Net Margin],[Internet Net Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Gross Sales (Bikes)",
            "expression": "CALCULATE([Internet Gross Sales],'Product'[Product Category] = \"Bikes\")",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############"
          },
          {
            "name": "Reseller Gross Sales (something)",
            "expression": "CALCULATE([Reseller Gross Sales],'Product'[Product Color] IN {\"Red\", \"White\"},Promotion[Discount Percentage] > .25)",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############"
          },
          {
            "name": "Internet Sales Customer Count",
            "description": "Unique customers who have purchased online.",
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT(Customer[Customer Alternate Key]),",
              "\t'Internet Sales')"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Internet Sales Customers Missing",
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT('Customer'[Customer Alternate Key]),",
              "\tFILTER(VALUES('Customer'[Customer Alternate Key]),",
              "\t\tISEMPTY(RELATEDTABLE('Internet Sales'))))",
              "\t"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Quick Check",
            "expression": "[Internet Sales Customer Count] + [Internet Sales Customers Missing]",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Internet Sales Products Missing",
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT('Product'[Product Alternate Key]),",
              "\tFILTER(VALUES('Product'[Product Alternate Key]),ISEMPTY(RELATEDTABLE('Internet Sales'))))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Internet Sales First Year Customer Count",
            "expression": [
              "",
              "CALCULATE([Internet Sales Customer Count],'Customer'[Customer History Segment] = \"First Year Customer\")"
            ],
            "formatString": "0"
          },
          {
            "name": "Internet Sales Products Missing (Accessories)",
            "expression": "CALCULATE([Internet Sales Products Missing],'Product'[Product Category] = \"Accessories\")",
            "formatString": "0"
          },
          {
            "name": "Internet Sales First Year and Accessory Customers",
            "expression": [
              "",
              "VAR FirstYearCustomers = ",
              "SUMMARIZE(",
              "\tCALCULATETABLE('Internet Sales',",
              "\t\t'Customer'[Customer History Segment] = \"First Year Customer\"),",
              "\t'Customer'[Customer Alternate Key])",
              "VAR AccessoryCustomersThisYear = ",
              "SUMMARIZE(",
              "CALCULATETABLE('Internet Sales',",
              "\t\t'Date'[Calendar Year Status] = \"Current Calendar Year\",'Product'[Product Category] = \"Accessories\"),",
              "'Customer'[Customer Alternate Key])",
              "VAR TargetCustomerSet = ",
              "DISTINCT(UNION(FirstYearCustomers,AccessoryCustomersThisYear))",
              "RETURN",
              "CALCULATE(DISTINCTCOUNT(Customer[Customer Alternate Key]),TargetCustomerSet)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "SummarizeColumnsCheck",
            "expression": [
              "",
              "COUNTROWS(SUMMARIZECOLUMNS('Customer'[Customer Alternate Key],CALCULATETABLE('Internet Sales','Product'[Product Category] = \"Accessories\")))"
            ],
            "formatString": "0"
          },
          {
            "name": "Internet Net Sales Product Rank",
            "expression": [
              "",
              "IF(HASONEVALUE('Product'[Product Alternate Key]),",
              "\tRANKX(ALL('Product'[Product Alternate Key]),[Internet Net Sales],,DESC,Skip),BLANK())"
            ],
            "formatString": "0"
          },
          {
            "name": "Internet Net Sales Product Rank (All Products)",
            "expression": [
              "",
              "VAR ProdRankTable = ",
              "ALL('Product'[Product Alternate Key],'Product'[Product Name],'Product'[Product Category Group],'Product'[Product Category],'Product'[Product Subcategory],'Product'[Product Name])",
              "RETURN",
              "RANKX(ProdRankTable,",
              "\t[Internet Net Sales],,DESC,Skip)"
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Internet Net Sales Product Rank (All Selected)",
            "expression": [
              "",
              "RANKX(ALLSELECTED('Product'),[Internet Net Sales],,DESC,Skip)"
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Internet Net Sales Product Rank (Conditional)",
            "expression": [
              "",
              "VAR SingleProduct = HASONEVALUE('Product'[Product Alternate Key])",
              "VAR SingleSubCat = HASONEVALUE('Product'[Product Subcategory])",
              "VAR SingleCat = HASONEVALUE('Product'[Product Category])",
              "RETURN",
              "Switch(TRUE(),",
              "\tSingleProduct = TRUE(), RANKX(ALL('Product'[Product Alternate Key],'Product'[Product Name]),[Internet Net Sales],,DESC,Skip),",
              "\tSingleSubCat = TRUE(), RANKX(ALL('Product'[Product Subcategory]),[Internet Net Sales],,DESC,Skip),",
              "\tSingleCat = TRUE(), RANKX(ALL('Product'[Product Category]),[Internet Net Sales],,DESC,Skip),",
              "\tBLANK())"
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Internet Net Sales Product Rank (New Conditional)",
            "expression": [
              "",
              "Switch(TRUE(),",
              "\tHASONEVALUE('Product'[Product Alternate Key]), RANKX(ALL('Product'[Product Alternate Key]),[Internet Net Sales],,DESC,Skip),",
              "\tHASONEVALUE('Product'[Product Subcategory]), RANKX(ALL('Product'[Product Subcategory]),[Internet Net Sales],,DESC,Skip),",
              "\tHASONEVALUE('Product'[Product Category]), RANKX(ALL('Product'[Product Category]),[Internet Net Sales],,DESC,Skip),",
              "\tBLANK())"
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Internet Net Sales Per Order",
            "expression": "DIVIDE([Internet Net Sales],[Internet Sales Orders])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales (Format Thousands)",
            "expression": "FORMAT([Internet Net Sales],\"$0,.0K\") ",
            "isHidden": true
          },
          {
            "name": "Internet Net Sales (Format Millions)",
            "expression": "FORMAT([Internet Net Sales],\"$0,,.0M\") ",
            "isHidden": true
          },
          {
            "name": "Internet Sales Below 150K",
            "expression": "IF([Internet Net Sales] <= 150000, [Internet Net Sales],BLANK())",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isHidden": true
          },
          {
            "name": "Internet Net Sales Per Order Below $600",
            "expression": "IF([Internet Net Sales Per Order] < 600,[Internet Net Sales Per Order],BLANK())",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isHidden": true
          },
          {
            "name": "Internet Net Sales Per Order Above $600",
            "expression": "IF([Internet Net Sales Per Order] >= 600, [Internet Net Sales Per Order],BLANK())",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isHidden": true
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1d2f5e3c-d316-454f-8fe8-c425b8bad4a9"
          },
          {
            "name": "LinkedQueryName",
            "value": "Internet Sales"
          }
        ]
      },
      {
        "name": "Reseller Sales",
        "description": "Sales transactions to Adventure Works resellers.",
        "columns": [
          {
            "name": "CustomerPONumber",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerPONumber",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "SalesOrderNumber",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SalesOrderNumber",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Discount Amount",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Discount Amount",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Freight",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Freight",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyCustom\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Order Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Order Quantity",
            "formatString": "#,0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" ThousandSeparator=\"True\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Tax Amount",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Tax Amount",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyCustom\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Unit Price",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyCustom\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Order Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Due Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Due Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Ship Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Ship Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Product Standard Cost",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Product Standard Cost",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyGeneral\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Currency Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Currency Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Currency Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Employee Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Employee Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Employee Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Reseller Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Reseller Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Reseller Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Product Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Sales Territory Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Sales Territory Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Sales Territory Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Promotion Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Promotion Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Promotion Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Reseller Sales-3d54a4a7-7624-4ae1-ad5d-ab187ead7fc5",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=#\"Reseller Sales\"",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Reseller Sales Purchase Orders",
            "expression": "DISTINCTCOUNT('Reseller Sales'[CustomerPONumber])",
            "formatString": "#,0"
          },
          {
            "name": "Reseller Sales Freight Cost",
            "expression": "sum('Reseller Sales'[Freight]) ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Sales Order Quantity",
            "expression": "sum('Reseller Sales'[Order Quantity]) ",
            "formatString": "#,0"
          },
          {
            "name": "Reseller Sales Discounts",
            "expression": "sum('Reseller Sales'[Discount Amount])"
          },
          {
            "name": "Reseller Gross Sales",
            "description": "The sum of unit price multiplied ordered quantity.",
            "expression": "SUMX('Reseller Sales','Reseller Sales'[Unit Price]*'Reseller Sales'[Order Quantity]) ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Net Sales",
            "description": "Reseller Gross Sales minus Reseller Sales Discounts.",
            "expression": "[Reseller Gross Sales] - [Reseller Sales Discounts]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Sales Product Cost",
            "description": "The sum of product standard cost multiplied by order quantity.",
            "expression": "SUMX('Reseller Sales','Reseller Sales'[Order Quantity]*'Reseller Sales'[Product Standard Cost]) ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Count of Products Sold",
            "expression": "CALCULATE(DISTINCTCOUNT('Product'[Product Alternate Key]),'Reseller Sales')",
            "formatString": "0"
          },
          {
            "name": "Reseller Gross Margin %",
            "description": "Reseller Gross Margin divied by Reseller Gross Sales.",
            "expression": "DIVIDE([Reseller Gross Margin],[Reseller Gross Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Last Monthly Reseller Net Sales",
            "expression": "CALCULATE([Reseller Net Sales],LASTNONBLANK('Date'[Calendar Year Month Number],[Reseller Net Sales]) )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Average Monthly Reseller Sales",
            "expression": "AVERAGEX(values('Date'[Calendar Year Month Number]),[Reseller Net Sales]) ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Trailing 6",
            "expression": [
              "",
              "VAR LastNonBlankMonth = LASTNONBLANK('Date'[Calendar Year Month Number],[Reseller Net Sales])",
              "VAR SixMonthsPrior = LastNonBlankMonth - 6",
              "RETURN",
              "CALCULATE([Reseller Net Sales],FILTER(ALL('Date'),'Date'[Calendar Year Month Number] <= LastNonBlankMonth-1 && 'Date'[Calendar Year Month Number] >= SixMonthsPrior))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Sales Average of Trailing 6 Months",
            "expression": [
              "",
              "VAR LastNonBlankMonth = LASTNONBLANK('Date'[Calendar Year Month Number],[Reseller Net Sales])",
              "VAR SixMonthsPrior = LastNonBlankMonth - 6",
              "RETURN",
              "CALCULATE(AVERAGEX(VALUES('Date'[Calendar Year Month Number]),[Reseller Net Sales]),FILTER(ALL('Date'),'Date'[Calendar Year Month Number] <= LastNonBlankMonth -1 && 'Date'[Calendar Year Month Number] >=SixMonthsPrior))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Sales Average Margin % of Trailing 6",
            "expression": [
              "",
              "VAR LastNonBlankMonth = LASTNONBLANK('Date'[Calendar Year Month Number],[Reseller Net Margin %])",
              "VAR SixMonthsPrior = LastNonBlankMonth - 6",
              "RETURN",
              "CALCULATE(AVERAGEX(VALUES('Date'[Calendar Year Month Number]),[Reseller Net Margin %]),FILTER(ALL('Date'),'Date'[Calendar Year Month Number] <= LastNonBlankMonth -1 && 'Date'[Calendar Year Month Number] >=SixMonthsPrior))"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "Reseller Sales Rows",
            "expression": "COUNTROWS('Reseller Sales')",
            "formatString": "#,0"
          },
          {
            "name": "Reseller Sales Margin Amt",
            "expression": "[Reseller Net Sales] - [Reseller Sales Product Cost] ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Net Sales (Bikes)",
            "expression": "CALCULATE([Reseller Net Sales],'Product'[Product Category] = \"Bikes\") ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Net Sales (Non-Bikes)",
            "expression": "CALCULATE([Reseller Net Sales],'Product'[Product Category Group] = \"Non-Bikes\") ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Net Sales (Non-Bikes %)",
            "expression": "DIVIDE([Reseller Net Sales (Non-Bikes)],[Reseller Net Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Count of Resellers",
            "expression": "DISTINCTCOUNT(Reseller[Reseller Key])",
            "formatString": "#,0"
          },
          {
            "name": "Count of Resellers with Sales",
            "expression": "CALCULATE([Count of Resellers],'Reseller Sales') ",
            "formatString": "#,0"
          },
          {
            "name": "Reseller Net Sales Rank (All)",
            "expression": "RANKX(ALL(Reseller),[Reseller Net Sales],,DESC,Skip)",
            "formatString": "#,0"
          },
          {
            "name": "Employee Count",
            "expression": "DISTINCTCOUNT(Employee[Employee Key])",
            "formatString": "0"
          },
          {
            "name": "Employee Count (CF)",
            "expression": "CALCULATE(DISTINCTCOUNT('Employee'[Employee Key]),CROSSFILTER('Reseller Sales'[Employee Key],'Employee'[Employee Key],Both))",
            "formatString": "0"
          },
          {
            "name": "reseller rows",
            "expression": "COUNTROWS('Reseller Sales')",
            "formatString": "0"
          },
          {
            "name": "Reseller Cost of Sales",
            "description": "Reseller Sales Product Cost plus Reseller Sales Freight Cost.",
            "expression": "[Reseller Sales Product Cost] + [Reseller Sales Freight Cost]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00"
          },
          {
            "name": "Reseller Gross Product Margin",
            "description": "Reseller Gross Sales minus Reseller Sales Product Cost.",
            "expression": "[Reseller Gross Sales] - [Reseller Sales Product Cost]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Gross Product Margin %",
            "description": "Reseller Gross Product Margin divided by Reseller Gross Sales.",
            "expression": "DIVIDE([Reseller Gross Product Margin],[Reseller Gross Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Reseller Net Product Margin",
            "description": "Reseller Net Sales minus Reseller Sales Product Cost.",
            "expression": "[Reseller Net Sales] - [Reseller Sales Product Cost]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############"
          },
          {
            "name": "Reseller Net Product Margin %",
            "description": "Reseller Net Product Margin divided by Reseller Net Sales.",
            "expression": "DIVIDE([Reseller Net Product Margin],[Reseller Net Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Reseller Gross Margin",
            "description": "Reseller Gross Sales minus Reseller Cost of Sales.",
            "expression": "[Reseller Gross Sales] - [Reseller Cost of Sales]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############"
          },
          {
            "name": "Reseller Net Margin",
            "description": "Reseller Net Sales minus Reseller Cost of Sales.",
            "expression": "[Reseller Net Sales] - [Reseller Cost of Sales]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############"
          },
          {
            "name": "Reseller Net Margin %",
            "description": "Reseller Net Margin divided by Reseller Net Sales.",
            "expression": "DIVIDE([Reseller Net Margin],[Reseller Net Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Legacy Reseller High Value Accessory and Clothing Products",
            "expression": [
              "",
              "/*",
              "Accessory category products with over 20K in net sales and over 32% net margin since last year ",
              "Clothing category products with over 55K in net sales and over 28% net margin since last year",
              "Enable filtering from dimension tables related to Reseller Sales",
              "*/",
              "VAR AccessorySales = 20000 VAR AccessoryNetMargin = .32",
              "VAR ClothingSales = 50000 VAR ClothingNetMargin = .28",
              "VAR CurrentAndPriorYear = CALCULATETABLE('Date','Date'[Calendar Year Status] IN {\"Current Calendar Year\", \"Prior Calendar Year\"})",
              "//Distinct Accessory Products",
              "VAR AccessoryProducts = ",
              "CALCULATE(DISTINCTCOUNT('Product'[Product Alternate Key]),",
              "\tCROSSFILTER('Reseller Sales'[Product Key],'Product'[Product Key],Both),",
              "\tCurrentAndPriorYear,",
              "\t'Product'[Product Category] = \"Accessories\",",
              "\tFILTER('Product',[Reseller Net Margin %] >= AccessoryNetMargin && [Reseller Net Sales] >= AccessorySales)",
              "\t)",
              "//Distinct Clothing Products",
              "VAR ClothingProducts = ",
              "CALCULATE(DISTINCTCOUNT('Product'[Product Alternate Key]),",
              "\tCROSSFILTER('Reseller Sales'[Product Key],'Product'[Product Key],Both),",
              "\tCurrentAndPriorYear,",
              "\t'Product'[Product Category] = \"Clothing\",",
              "\tFILTER('Product',[Reseller Net Margin %] >= ClothingNetMargin && [Reseller Net Sales] > ClothingSales)",
              "\t)",
              "RETURN",
              "AccessoryProducts + ClothingProducts"
            ],
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Reseller High Value Accessory and Clothing Products",
            "expression": [
              "",
              "/*",
              "Accessory category products with over 20K in net sales and over 32% net margin since last year ",
              "Clothing category products with over 55K in net sales and over 28% net margin since last year",
              "Enable filtering from dimension tables related to Reseller Sales",
              "*/",
              "VAR AccessorySales = 20000 VAR AccessoryNetMargin = .32",
              "VAR ClothingSales = 50000 VAR ClothingNetMargin = .28",
              "//Distinct Accessory Products",
              "VAR AccessoryProducts = ",
              "CALCULATE(DISTINCTCOUNT('Product'[Product Alternate Key]),",
              "\t\tFILTER(",
              "\t\tSUMMARIZE(",
              "\t\tCALCULATETABLE('Reseller Sales',",
              "\t\t\t'Date'[Calendar Year Status] IN {\"Current Calendar Year\", \"Prior Calendar Year\"},",
              "\t\t\t'Product'[Product Category] = \"Accessories\"),",
              "\t\t\t'Product'[Product Alternate Key]),",
              "\t\t\t[Reseller Net Margin %] >= AccessoryNetMargin && [Reseller Net Sales] >= AccessorySales))",
              "//Distinct Clothing Products",
              "VAR ClothingProducts = ",
              "CALCULATE(DISTINCTCOUNT('Product'[Product Alternate Key]),",
              "\t\tFILTER(",
              "\t\tSUMMARIZE(",
              "\t\tCALCULATETABLE('Reseller Sales',",
              "\t\t\t'Date'[Calendar Year Status] IN {\"Current Calendar Year\", \"Prior Calendar Year\"},",
              "\t\t\t'Product'[Product Category] = \"Clothing\"),",
              "\t\t\t'Product'[Product Alternate Key]),",
              "\t\t\t[Reseller Net Margin %] >= ClothingNetMargin && [Reseller Net Sales] > ClothingSales)",
              "\t)",
              "RETURN",
              "AccessoryProducts + ClothingProducts"
            ],
            "formatString": "0"
          },
          {
            "name": "New Reseller High Value Accessory and Clothing Products",
            "expression": [
              "",
              "/*",
              "Accessory category products with over 20K in net sales and over 32% net margin since last year ",
              "Clothing category products with over 55K in net sales and over 28% net margin since last year",
              "Enable filtering from dimension tables related to Reseller Sales",
              "*/",
              "VAR AccessorySales = 20000 VAR AccessoryNetMargin = .32",
              "VAR ClothingSales = 50000 VAR ClothingNetMargin = .28",
              "//Distinct Accessory Products",
              "VAR AccessoryProducts = ",
              "CALCULATE(DISTINCTCOUNT('Product'[Product Alternate Key]),",
              "\t\tFILTER(",
              "\t\tFILTER(",
              "\t\tSUMMARIZE(",
              "\t\tCALCULATETABLE('Reseller Sales',",
              "\t\t\t'Date'[Calendar Year Status] IN {\"Current Calendar Year\", \"Prior Calendar Year\"},",
              "\t\t\t'Product'[Product Category] = \"Accessories\"),",
              "\t\t\t'Product'[Product Alternate Key]),",
              "\t\t\t[Reseller Net Margin %] >= AccessoryNetMargin), ",
              "\t\t\t[Reseller Net Sales] >= AccessorySales))",
              "//Distinct Clothing Products",
              "VAR ClothingProducts = ",
              "CALCULATE(DISTINCTCOUNT('Product'[Product Alternate Key]),",
              "\t\tFILTER(",
              "\t\tFILTER(",
              "\t\tSUMMARIZE(",
              "\t\tCALCULATETABLE('Reseller Sales',",
              "\t\t\t'Date'[Calendar Year Status] IN {\"Current Calendar Year\", \"Prior Calendar Year\"},",
              "\t\t\t'Product'[Product Category] = \"Clothing\"),",
              "\t\t\t'Product'[Product Alternate Key]),",
              "\t\t\t[Reseller Net Margin %] >= ClothingNetMargin),",
              "\t\t\t [Reseller Net Sales] >= ClothingSales)",
              "\t)",
              "RETURN",
              "AccessoryProducts + ClothingProducts"
            ],
            "formatString": "0"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "484e1337-ef14-4499-b31f-a9015fbf2a21"
          },
          {
            "name": "LinkedQueryName",
            "value": "Reseller Sales"
          }
        ]
      },
      {
        "name": "Date",
        "columns": [
          {
            "name": "Calendar Month",
            "dataType": "string",
            "sourceColumn": "Calendar Month",
            "sortByColumn": "Calendar Month Number",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Calendar Year",
            "dataType": "int64",
            "sourceColumn": "Calendar Year",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Calendar Yr-Mo",
            "dataType": "string",
            "sourceColumn": "Calendar Yr-Mo",
            "sortByColumn": "Calendar Year Month Number",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Calendar Yr-Qtr",
            "dataType": "string",
            "sourceColumn": "Calendar Yr-Qtr",
            "sortByColumn": "Calendar Year Quarter Number",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Calendar Yr-Wk",
            "dataType": "string",
            "sourceColumn": "Calendar Yr-Wk",
            "sortByColumn": "Calendar Year Week Number",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Fiscal Quarter",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Fiscal Quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Fiscal Period",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Period",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Weekday Sort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Weekday Sort",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Weekday Abb",
            "dataType": "string",
            "sourceColumn": "Weekday Abb",
            "sortByColumn": "Weekday Sort",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Weekday",
            "dataType": "string",
            "sourceColumn": "Weekday",
            "sortByColumn": "Weekday Sort",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Fiscal Yr-Wk Sort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Yr-Wk Sort",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Fiscal Yr-Wk",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Fiscal Yr-Wk",
            "sortByColumn": "Fiscal Yr-Wk Sort",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Fiscal Yr-Qtr",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Fiscal Yr-Qtr",
            "sortByColumn": "Fiscal Yr-Qtr Sort",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Fiscal Yr-Period",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Fiscal Yr-Period",
            "sortByColumn": "Fiscal Yr-Period Sort",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Fiscal Yr-Period Sort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Yr-Period Sort",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Fiscal Year",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Year",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Fiscal Week Sort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Week Sort",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Fiscal Yr-Qtr Sort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Yr-Qtr Sort",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Fiscal Date Last Year",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Fiscal Date Last Year",
            "formatString": "m/d/yy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Fiscal Week Sequence",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Week Sequence",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Fiscal Week of Period",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Week of Period",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Calendar Year Status",
            "dataType": "string",
            "sourceColumn": "Calendar Year Status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "name": "Prior Calendar Year Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Prior Calendar Year Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Calendar Month Status",
            "dataType": "string",
            "sourceColumn": "Calendar Month Status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "name": "Calendar Month Number",
            "dataType": "int64",
            "sourceColumn": "Calendar Month Number",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Calendar Year Month Number",
            "dataType": "int64",
            "sourceColumn": "Calendar Year Month Number",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Date Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Date Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Date Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Date Number",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Calendar Week in Year",
            "dataType": "string",
            "sourceColumn": "Calendar Week in Year",
            "sortByColumn": "Calendar Week Number in Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Calendar Week in Year"
              }
            ]
          },
          {
            "name": "Calendar Week Number in Year",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Calendar Week Number in Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Calendar Year Week Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Calendar Year Week Number",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Calendar Year Quarter Number",
            "dataType": "int64",
            "sourceColumn": "Calendar Year Quarter Number",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Full Date Description",
            "dataType": "string",
            "sourceColumn": "Full Date Description",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "name": "Day Number in Calendar Month",
            "dataType": "int64",
            "sourceColumn": "Day Number in Calendar Month",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Day Number in Calendar Year",
            "dataType": "int64",
            "sourceColumn": "Day Number in Calendar Year",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Calendar Quarter in Year",
            "dataType": "string",
            "sourceColumn": "Calendar Quarter in Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "name": "Calendar Quarter Number in Year",
            "dataType": "int64",
            "sourceColumn": "Calendar Quarter Number in Year",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Weekday Indicator",
            "dataType": "string",
            "sourceColumn": "Weekday Indicator",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "name": "Holiday Indicator",
            "dataType": "string",
            "sourceColumn": "Holiday Indicator",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "name": "Calendar Week in Month",
            "dataType": "int64",
            "sourceColumn": "Calendar Week in Month",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Calendar Week Ending Date",
            "dataType": "dateTime",
            "sourceColumn": "Calendar Week Ending Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              }
            ]
          },
          {
            "name": "Prior Calendar Month Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Prior Calendar Month Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Calendar Week Status",
            "dataType": "string",
            "sourceColumn": "Calendar Week Status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Calendar Week Status"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "One Year Prior Date",
            "dataType": "dateTime",
            "sourceColumn": "One Year Prior Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "One Year Prior Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "DST Flag",
            "dataType": "string",
            "sourceColumn": "DST Flag",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "DST Flag"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Prior Calendar Week Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Prior Calendar Week Date",
            "formatString": "dddd\\, mmmm d\\, yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongDate\" FormatString=\"dddd, MMMM d, yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Prior Calendar Week Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Calendar Month Ending Date",
            "dataType": "dateTime",
            "sourceColumn": "Calendar Month Ending Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Calendar Month Ending Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Trailing 3 Calendar Month Periods",
            "dataType": "string",
            "sourceColumn": "Trailing 3 Calendar Month Periods",
            "sortByColumn": "Trailing 3 Calendar Month Period Sort",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Trailing 3 Calendar Month Periods"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Trailing 3 Calendar Month Period Sort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Trailing 3 Calendar Month Period Sort",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Trailing 3 Calendar Month Period Sort"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date-5ecfecd0-bb64-4070-a6cd-4ee719af0a71",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=Date",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Selected Calendar Year",
            "description": "The currently selected calendar year",
            "expression": [
              "",
              "VAR CalYear = SELECTEDVALUE('Date'[Calendar Year], \"Multiple Years\")",
              "RETURN \"Calendar Year: \" & CalYear"
            ],
            "isHidden": true
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar Hierarchy",
            "levels": [
              {
                "name": "Calendar Year",
                "ordinal": 0,
                "column": "Calendar Year"
              },
              {
                "name": "Calendar Yr-Qtr",
                "ordinal": 1,
                "column": "Calendar Yr-Qtr"
              },
              {
                "name": "Calendar Yr-Wk",
                "ordinal": 3,
                "column": "Calendar Yr-Wk"
              },
              {
                "name": "Date",
                "ordinal": 4,
                "column": "Date"
              },
              {
                "name": "Calendar Yr-Mo",
                "ordinal": 2,
                "column": "Calendar Yr-Mo"
              }
            ]
          },
          {
            "name": "Fiscal Year Hierarchy",
            "isHidden": true,
            "levels": [
              {
                "name": "Fiscal Year",
                "ordinal": 0,
                "column": "Fiscal Year"
              },
              {
                "name": "Fiscal Yr-Qtr",
                "ordinal": 1,
                "column": "Fiscal Yr-Qtr"
              },
              {
                "name": "Fiscal Yr-Period",
                "ordinal": 2,
                "column": "Fiscal Yr-Period"
              },
              {
                "name": "Fiscal Yr-Wk",
                "ordinal": 3,
                "column": "Fiscal Yr-Wk"
              },
              {
                "name": "Date",
                "ordinal": 4,
                "column": "Date"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "600019e5-bef3-41c2-b0ee-d43747785df6"
          },
          {
            "name": "LinkedQueryName",
            "value": "Date"
          }
        ]
      },
      {
        "name": "Promotion",
        "columns": [
          {
            "name": "Discount Percentage",
            "dataType": "double",
            "sourceColumn": "Discount Percentage",
            "formatString": "0%;-0%;0%",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Percentage\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Promotion",
            "dataType": "string",
            "sourceColumn": "Promotion",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Promotion Type",
            "dataType": "string",
            "sourceColumn": "Promotion Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Start Date",
            "dataType": "dateTime",
            "sourceColumn": "Start Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "End Date",
            "dataType": "dateTime",
            "sourceColumn": "End Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Max Quantity",
            "dataType": "int64",
            "sourceColumn": "Max Quantity",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Min Quantity",
            "dataType": "int64",
            "sourceColumn": "Min Quantity",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Promotion Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Promotion Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Promotion Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Promotion-0ec5353c-37f3-458e-9443-820869f8930e",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=Promotion",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Promotion Type Hierarchy",
            "levels": [
              {
                "name": "Promotion Type",
                "ordinal": 0,
                "column": "Promotion Type"
              },
              {
                "name": "Promotion",
                "ordinal": 1,
                "column": "Promotion"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7219382d-2c02-46d3-82ea-56db81919b88"
          },
          {
            "name": "LinkedQueryName",
            "value": "Promotion"
          }
        ]
      },
      {
        "name": "Currency",
        "columns": [
          {
            "name": "Currency",
            "dataType": "string",
            "sourceColumn": "Currency",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Currency"
              }
            ]
          },
          {
            "name": "Currency Abbrev",
            "dataType": "string",
            "sourceColumn": "Currency Abbrev",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Currency Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Currency Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Currency Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Currency-55ed461a-b03f-441d-a3fb-98a977343060",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=Currency",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cacde308-15b6-4464-ae27-1ccd796820d2"
          },
          {
            "name": "LinkedQueryName",
            "value": "Currency"
          }
        ]
      },
      {
        "name": "Product",
        "description": "Adventure Works product catalog including products not yet for sale.",
        "columns": [
          {
            "name": "Product Class",
            "dataType": "string",
            "sourceColumn": "Product Class",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Color",
            "dataType": "string",
            "sourceColumn": "Product Color",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Start Date",
            "dataType": "dateTime",
            "sourceColumn": "Product Start Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Product End Date",
            "dataType": "dateTime",
            "sourceColumn": "Product End Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Product Description",
            "dataType": "string",
            "sourceColumn": "Product Description",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "Product Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Model",
            "dataType": "string",
            "sourceColumn": "Product Model",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Weight",
            "dataType": "double",
            "sourceColumn": "Product Weight",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Product Status",
            "dataType": "string",
            "sourceColumn": "Product Status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Subcategory",
            "dataType": "string",
            "sourceColumn": "Product Subcategory",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Category",
            "dataType": "string",
            "sourceColumn": "Product Category",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Safety Stock Level",
            "dataType": "int64",
            "sourceColumn": "Product Safety Stock Level",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              }
            ]
          },
          {
            "name": "Product Category Group",
            "dataType": "string",
            "sourceColumn": "Product Category Group",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "sourceColumn": "Product Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Product Alternate Key",
            "dataType": "string",
            "description": "The natural key of the product.",
            "sourceColumn": "Product Alternate Key",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "name": "Product Days to Manufacture",
            "dataType": "int64",
            "sourceColumn": "Product Days to Manufacture",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Product Days to Manufacture"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Product Dealer Price",
            "dataType": "decimal",
            "sourceColumn": "Product Dealer Price",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyCustom\" Accuracy=\"0\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Product Dealer Price"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Product Finished Goods Indicator",
            "dataType": "string",
            "sourceColumn": "Product Finished Goods Indicator",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Product Finished Goods Indicator"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Product List Price",
            "dataType": "decimal",
            "sourceColumn": "Product List Price",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyCustom\" Accuracy=\"0\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Product List Price"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Product Standard Cost",
            "dataType": "decimal",
            "sourceColumn": "Product Standard Cost",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyCustom\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Product Standard Cost"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Product Line",
            "dataType": "string",
            "sourceColumn": "Product Line",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Product Line"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Product Style",
            "dataType": "string",
            "sourceColumn": "Product Style",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Product Style"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Product-0a4b9d8b-d732-4ac6-852a-1d5f4d431b46",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=Product",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Selected Product Name",
            "expression": [
              "",
              "VAR ProdName = SELECTEDVALUE('Product'[Product Name], \"Multiple Product Names\")",
              "RETURN \"Product Name: \" & ProdName"
            ],
            "isHidden": true
          },
          {
            "name": "Selected Product Subcategory",
            "expression": [
              "",
              "VAR ProdSubcat = SELECTEDVALUE('Product'[Product Subcategory], \"Multiple Product Subcateogies\")",
              "RETURN \"Product Subcategory: \" & ProdSubcat"
            ],
            "isHidden": true
          },
          {
            "name": "Distinct Count of Products",
            "expression": "DISTINCTCOUNT('Product'[Product Alternate Key])",
            "formatString": "#,0",
            "isHidden": true
          }
        ],
        "hierarchies": [
          {
            "name": "Product Hierarchy",
            "levels": [
              {
                "name": "Product Category Group",
                "ordinal": 0,
                "column": "Product Category Group"
              },
              {
                "name": "Product Category",
                "ordinal": 1,
                "column": "Product Category"
              },
              {
                "name": "Product Subcategory",
                "ordinal": 2,
                "column": "Product Subcategory"
              },
              {
                "name": "Product Name",
                "ordinal": 3,
                "column": "Product Name"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1266370b-2cfa-4506-a42f-6df77c488901"
          },
          {
            "name": "LinkedQueryName",
            "value": "Product"
          }
        ]
      },
      {
        "name": "Sales Territory",
        "description": "Adventure Works sales territory structure (Group, Country, Region).",
        "columns": [
          {
            "name": "Sales Territory Group",
            "dataType": "string",
            "sourceColumn": "Sales Territory Group",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Territory Country",
            "dataType": "string",
            "sourceColumn": "Sales Territory Country",
            "dataCategory": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Territory Region",
            "dataType": "string",
            "sourceColumn": "Sales Territory Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Territory URL",
            "dataType": "string",
            "sourceColumn": "Sales Territory URL",
            "dataCategory": "ImageUrl",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Sales Territory URL"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Sales Territory Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Sales Territory Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Sales Territory Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sales Territory-7bd565aa-9325-482a-81ab-1ce42e39d224",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=#\"Sales Territory\"",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Sales Territory Hierarchy",
            "levels": [
              {
                "name": "Sales Territory Region",
                "ordinal": 2,
                "column": "Sales Territory Region"
              },
              {
                "name": "Sales Territory Group",
                "ordinal": 0,
                "column": "Sales Territory Group"
              },
              {
                "name": "Sales Territory Country",
                "ordinal": 1,
                "column": "Sales Territory Country"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e514a187-466f-42e7-9194-d5a32032b355"
          },
          {
            "name": "LinkedQueryName",
            "value": "Sales Territory"
          }
        ]
      },
      {
        "name": "Reseller",
        "columns": [
          {
            "name": "Year Opened",
            "dataType": "int64",
            "sourceColumn": "Year Opened",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Bank Name",
            "dataType": "string",
            "sourceColumn": "Bank Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Business Type",
            "dataType": "string",
            "sourceColumn": "Business Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Year of First Order",
            "dataType": "int64",
            "sourceColumn": "Year of First Order",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Year of Last Order",
            "dataType": "int64",
            "sourceColumn": "Year of Last Order",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Reseller Annual Sales",
            "dataType": "decimal",
            "sourceColumn": "Reseller Annual Sales",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Reseller Phone",
            "dataType": "string",
            "sourceColumn": "Reseller Phone",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Number of Employees",
            "dataType": "int64",
            "sourceColumn": "Number of Employees",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Annual Revenue",
            "dataType": "decimal",
            "sourceColumn": "Annual Revenue",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Reseller Address",
            "dataType": "string",
            "sourceColumn": "Reseller Address",
            "dataCategory": "Address",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Reseller City",
            "dataType": "string",
            "sourceColumn": "Reseller City",
            "dataCategory": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Reseller Country Code",
            "dataType": "string",
            "sourceColumn": "Reseller Country Code",
            "dataCategory": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Reseller Country",
            "dataType": "string",
            "sourceColumn": "Reseller Country",
            "dataCategory": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Reseller Zip Code",
            "dataType": "string",
            "sourceColumn": "Reseller Zip Code",
            "dataCategory": "PostalCode",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Reseller State Province",
            "dataType": "string",
            "sourceColumn": "Reseller State Province",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Reseller State Province Code",
            "dataType": "string",
            "sourceColumn": "Reseller State Province Code",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Minimum Payment Amt",
            "dataType": "decimal",
            "sourceColumn": "Minimum Payment Amt",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Reseller Product Line",
            "dataType": "string",
            "sourceColumn": "Reseller Product Line",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Reseller Order Frequency",
            "dataType": "string",
            "sourceColumn": "Reseller Order Frequency",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Reseller Order Month",
            "dataType": "int64",
            "sourceColumn": "Reseller Order Month",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Reseller Sales Territory Country",
            "dataType": "string",
            "sourceColumn": "Reseller Sales Territory Country",
            "dataCategory": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Reseller Sales Territory Group",
            "dataType": "string",
            "sourceColumn": "Reseller Sales Territory Group",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Reseller Sales Territory Region",
            "dataType": "string",
            "sourceColumn": "Reseller Sales Territory Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Reseller Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Reseller Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Reseller Alternate Key",
            "dataType": "string",
            "sourceColumn": "Reseller Alternate Key",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Reseller Alternate Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Reseller City State",
            "dataType": "string",
            "sourceColumn": "Reseller City State",
            "dataCategory": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Reseller City State"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Reseller Name",
            "dataType": "string",
            "sourceColumn": "Reseller Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Reseller Name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Reseller-0c76e1bb-e74d-4ab4-b6c7-c8426025a6cc",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=Reseller",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Reseller Sales Territory Group Hierarchy",
            "levels": [
              {
                "name": "Reseller Sales Territory Group",
                "ordinal": 0,
                "column": "Reseller Sales Territory Group"
              },
              {
                "name": "Reseller Sales Territory Country",
                "ordinal": 1,
                "column": "Reseller Sales Territory Country"
              },
              {
                "name": "Reseller Sales Territory Region",
                "ordinal": 2,
                "column": "Reseller Sales Territory Region"
              }
            ]
          },
          {
            "name": "Reseller Country Hierarchy",
            "levels": [
              {
                "name": "Reseller Country",
                "ordinal": 0,
                "column": "Reseller Country"
              },
              {
                "name": "Reseller City State",
                "ordinal": 2,
                "column": "Reseller City State"
              },
              {
                "name": "Reseller State Province",
                "ordinal": 1,
                "column": "Reseller State Province"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "980acd1b-642c-43f6-8090-11a56c70c816"
          },
          {
            "name": "LinkedQueryName",
            "value": "Reseller"
          }
        ]
      },
      {
        "name": "Employee",
        "description": "Adventure Works employees including their history.",
        "columns": [
          {
            "name": "Employee Last Name",
            "dataType": "string",
            "sourceColumn": "Employee Last Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Name",
            "dataType": "string",
            "sourceColumn": "Employee Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Email Address",
            "dataType": "string",
            "sourceColumn": "Employee Email Address",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Department",
            "dataType": "string",
            "sourceColumn": "Employee Department",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Gender",
            "dataType": "string",
            "sourceColumn": "Employee Gender",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Marital Status",
            "dataType": "string",
            "sourceColumn": "Employee Marital Status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Title",
            "dataType": "string",
            "sourceColumn": "Employee Title",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Phone",
            "dataType": "string",
            "sourceColumn": "Employee Phone",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Login ID",
            "dataType": "string",
            "sourceColumn": "Employee Login ID",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Current Flag",
            "dataType": "string",
            "sourceColumn": "Current Flag",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Salaried Flag",
            "dataType": "string",
            "sourceColumn": "Salaried Flag",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Status",
            "dataType": "string",
            "sourceColumn": "Employee Status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Sales Territory Country",
            "dataType": "string",
            "sourceColumn": "Employee Sales Territory Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Sales Territory Group",
            "dataType": "string",
            "sourceColumn": "Employee Sales Territory Group",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Sales Territory Region",
            "dataType": "string",
            "sourceColumn": "Employee Sales Territory Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Alternate Key",
            "dataType": "string",
            "sourceColumn": "Employee Alternate Key",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Employee Alternate Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Employee Row Start Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Employee Row Start Date",
            "formatString": "dddd\\, mmmm d\\, yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongDate\" FormatString=\"dddd, MMMM d, yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Employee Row Start Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Employee Row End Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Employee Row End Date",
            "formatString": "dddd\\, mmmm d\\, yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongDate\" FormatString=\"dddd, MMMM d, yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Employee Row End Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Employee Manager Last Name",
            "dataType": "string",
            "sourceColumn": "Employee Manager Last Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Employee Manager Last Name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Employee Manager Name",
            "dataType": "string",
            "sourceColumn": "Employee Manager Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Employee Manager Name"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Employee Base Rate",
            "dataType": "decimal",
            "sourceColumn": "Employee Base Rate",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyGeneral\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Employee Base Rate"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Employee Hire Date",
            "dataType": "dateTime",
            "sourceColumn": "Employee Hire Date",
            "formatString": "dddd\\, mmmm d\\, yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongDate\" FormatString=\"dddd, MMMM d, yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Employee Hire Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Employee Pay Frequency",
            "dataType": "int64",
            "sourceColumn": "Employee Pay Frequency",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Employee Pay Frequency"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Employee Vacation Hours",
            "dataType": "int64",
            "sourceColumn": "Employee Vacation Hours",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Employee Vacation Hours"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Employee Email Link",
            "dataType": "string",
            "sourceColumn": "Employee Email Link",
            "dataCategory": "WebUrl",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Employee Email Link"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Employee Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Employee Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Employee Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Parent Employee Key",
            "dataType": "int64",
            "sourceColumn": "Parent Employee Key",
            "formatString": "0",
            "summarizeBy": "count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Parent Employee Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Employee-390bd832-e409-4f57-894b-2f9e7930ef42",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=Employee",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "51f48784-7e10-4be7-8b42-56636f340ddc"
          },
          {
            "name": "LinkedQueryName",
            "value": "Employee"
          }
        ]
      },
      {
        "name": "BridgeBudgetDate",
        "isHidden": true,
        "columns": [
          {
            "name": "Calendar Yr-Mo",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Calendar Yr-Mo",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "BridgeBudgetDate-b9b29560-7e2e-4f56-81e3-397b6b4a03c0",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=BridgeBudgetDate",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "38006a37-699d-4d19-93bc-3cfb64d72a95"
          },
          {
            "name": "LinkedQueryName",
            "value": "BridgeBudgetDate"
          }
        ]
      },
      {
        "name": "BridgeProductSubCat",
        "isHidden": true,
        "columns": [
          {
            "name": "Product Subcategory",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Subcategory",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "BridgeProductSubCat-329393de-e0fe-456a-ae10-f620d8a4d161",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=BridgeProductSubCat",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0c21c50d-b203-43ff-8a2b-83a7f27d785d"
          },
          {
            "name": "LinkedQueryName",
            "value": "BridgeProductSubCat"
          }
        ]
      },
      {
        "name": "Customer",
        "description": "Customers who've made a purchase online.",
        "columns": [
          {
            "name": "Customer Name",
            "dataType": "string",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              }
            ]
          },
          {
            "name": "Customer History Segment",
            "dataType": "string",
            "description": "Four customer segments (1st Year, 2nd Year, 3rd Year, and Legacy) based on first purchase date relative to current date.",
            "sourceColumn": "Customer History Segment",
            "sortByColumn": "Customer History Segment Sort",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer History Segment"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer First Purchase Date",
            "dataType": "dateTime",
            "sourceColumn": "Customer First Purchase Date",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer First Purchase Date"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Title",
            "dataType": "string",
            "sourceColumn": "Customer Title",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Title"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Street Address",
            "dataType": "string",
            "sourceColumn": "Customer Street Address",
            "dataCategory": "Address",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Street Address"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Date of Birth",
            "dataType": "dateTime",
            "sourceColumn": "Customer Date of Birth",
            "formatString": "dddd\\, mmmm d\\, yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongDate\" FormatString=\"dddd, MMMM d, yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Date of Birth"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Commute Distance",
            "dataType": "string",
            "sourceColumn": "Customer Commute Distance",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Commute Distance"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Alternate Key",
            "dataType": "string",
            "sourceColumn": "Customer Alternate Key",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Alternate Key"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Email Address",
            "dataType": "string",
            "sourceColumn": "Customer Email Address",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Email Address"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Education",
            "dataType": "string",
            "sourceColumn": "Customer Education",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Education"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Occupation",
            "dataType": "string",
            "sourceColumn": "Customer Occupation",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Occupation"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Gender",
            "dataType": "string",
            "sourceColumn": "Customer Gender",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Gender"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer House Owner Indicator",
            "dataType": "string",
            "sourceColumn": "Customer House Owner Indicator",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer House Owner Indicator"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Cars Owned",
            "dataType": "int64",
            "sourceColumn": "Customer Cars Owned",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Cars Owned"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Marital Status",
            "dataType": "string",
            "sourceColumn": "Customer Marital Status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Marital Status"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Children",
            "dataType": "int64",
            "sourceColumn": "Customer Children",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Children"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Phone Number",
            "dataType": "string",
            "sourceColumn": "Customer Phone Number",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Phone Number"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Annual Income",
            "dataType": "decimal",
            "sourceColumn": "Customer Annual Income",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyGeneral\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Annual Income"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer City",
            "dataType": "string",
            "sourceColumn": "Customer City",
            "dataCategory": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer City"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Country Code",
            "dataType": "string",
            "sourceColumn": "Customer Country Code",
            "dataCategory": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Country Code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Country",
            "dataType": "string",
            "sourceColumn": "Customer Country",
            "dataCategory": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Country"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Postal Code",
            "dataType": "string",
            "sourceColumn": "Customer Postal Code",
            "dataCategory": "PostalCode",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Postal Code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer State Province",
            "dataType": "string",
            "sourceColumn": "Customer State Province",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer State Province"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer State Province Code",
            "dataType": "string",
            "sourceColumn": "Customer State Province Code",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer State Province Code"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer City State",
            "dataType": "string",
            "sourceColumn": "Customer City State",
            "dataCategory": "City",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer City State"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Sales Territory Country",
            "dataType": "string",
            "sourceColumn": "Customer Sales Territory Country",
            "dataCategory": "Country",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Sales Territory Country"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Sales Territory Group",
            "dataType": "string",
            "sourceColumn": "Customer Sales Territory Group",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Sales Territory Group"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Sales Territory Region",
            "dataType": "string",
            "sourceColumn": "Customer Sales Territory Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Sales Territory Region"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer History Segment Sort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Customer History Segment Sort",
            "formatString": "0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer History Segment Sort"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Customer Full Address",
            "dataType": "string",
            "sourceColumn": "Customer Full Address",
            "dataCategory": "Address",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Customer Full Address"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Customer-f7fc3ad2-5f96-40ba-becd-542271b80859",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=Customer",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Brett Set Based Validation Test",
            "expression": [
              "",
              "VAR MaleCustomers = ",
              "CALCULATETABLE(VALUES('Customer'[Customer Alternate Key]),",
              "\tCROSSFILTER('Internet Sales'[Customer Key],'Customer'[Customer Key],Both),",
              "\t'Customer'[Customer Gender] = \"Male\"",
              "                )",
              "VAR AccessoryCustomersThisYear = ",
              "CALCULATETABLE(VALUES('Customer'[Customer Alternate Key]),",
              "\tCROSSFILTER('Internet Sales'[Customer Key],'Customer'[Customer Key],Both),",
              "\t'Date'[Calendar Year Status] = \"Current Calendar Year\",",
              "\t'Product'[Product Category] = \"Accessories\"",
              "                )",
              "VAR TargetCustomerSet = ",
              "DISTINCT(UNION(MaleCustomers,AccessoryCustomersThisYear))",
              "RETURN",
              "CALCULATE(DISTINCTCOUNT(Customer[Customer Alternate Key]),TargetCustomerSet)"
            ],
            "formatString": "#,0",
            "isHidden": true
          }
        ],
        "hierarchies": [
          {
            "name": "Customer Country Hierarchy",
            "levels": [
              {
                "name": "Customer Country",
                "ordinal": 0,
                "column": "Customer Country"
              },
              {
                "name": "Customer State Province",
                "ordinal": 1,
                "column": "Customer State Province"
              },
              {
                "name": "Customer City State",
                "ordinal": 2,
                "column": "Customer City State"
              }
            ]
          },
          {
            "name": "Customer Country Code Hierarchy",
            "levels": [
              {
                "name": "Customer Country Code",
                "ordinal": 0,
                "column": "Customer Country Code"
              },
              {
                "name": "Customer State Province Code",
                "ordinal": 1,
                "column": "Customer State Province Code"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d704295a-28a4-4c9b-b5f6-9034c5c7116f"
          },
          {
            "name": "LinkedQueryName",
            "value": "Customer"
          }
        ]
      },
      {
        "name": "Date Intelligence Metrics",
        "description": "A collection of measures which apply custom date filters to other measures.",
        "columns": [
          {
            "name": "Dummy",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Dummy",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date Intelligence Metrics-07292a4b-2e41-4f18-87c8-c83f38ba07d3",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=#\"Date Intelligence Metrics\"",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Internet Net Sales (PYTD)",
            "expression": [
              "CALCULATE([Internet Net Sales],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t\t\t))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Net Sales (CY)",
            "expression": [
              "CALCULATE([Reseller Net Sales],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ]
          },
          {
            "name": "Reseller Net Sales (PY)",
            "expression": [
              "CALCULATE([Reseller Net Sales],FILTER(ALL('Date'),",
              "\tCONTAINS(VALUES('Date'[Prior Calendar Year Date]),'Date'[Prior Calendar Year Date],'Date'[Date])))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Net Sales (PYTD)",
            "expression": [
              "CALCULATE([Reseller Net Sales],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1  &&",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t\t\t))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Net Sales (YTD)",
            "expression": [
              "CALCULATE([Reseller Net Sales],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Margin % (YTD)",
            "expression": [
              "CALCULATE([Internet Sales Margin %],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Sales Margin % (CY)",
            "expression": [
              "CALCULATE([Internet Sales Margin %],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year Status] = \"Current Calendar Year\" && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Sales Margin % (PYTD)",
            "expression": [
              "CALCULATE([Internet Sales Margin %],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) - 1 && ",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t\t\t))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Sales Margin % (PY)",
            "expression": [
              "CALCULATE([Internet Sales Margin %],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year Status] = \"Prior Calendar Year\" && ",
              "\t'Date'[Calendar Year Month Number] = MAX('Date'[Calendar Year Month Number]) - 12 &&",
              "\t'Date'[Date] >= MIN('Date'[Prior Calendar Year Date]) && 'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "AdWorks Net Sales (YTD)",
            "expression": [
              "CALCULATE([AdWorks Net Sales],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Net Sales (CY)",
            "expression": [
              "CALCULATE([AdWorks Net Sales],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Net Sales (PYTD)",
            "expression": [
              "CALCULATE([AdWorks Net Sales],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t\t\t))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Net Sales (PY)",
            "expression": [
              "CALCULATE([AdWorks Net Sales],FILTER(ALL('Date'),",
              "\tCONTAINS(VALUES('Date'[Prior Calendar Year Date]),'Date'[Prior Calendar Year Date],'Date'[Date])))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Customer Count (YTD)",
            "expression": [
              "CALCULATE([Internet Sales Customer Count],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Internet Sales Customer Count (CY)",
            "expression": [
              "CALCULATE([Internet Sales Customer Count],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Internet Sales Customer Count (PY)",
            "expression": [
              "CALCULATE([Internet Sales Customer Count],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t'Date'[Calendar Year Month Number] = MAX('Date'[Calendar Year Month Number]) - 12 &&",
              "\t'Date'[Date] >= MIN('Date'[Prior Calendar Year Date]) && 'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Internet Sales Customer Count (PYTD)",
            "expression": [
              "CALCULATE([Internet Sales Customer Count],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t\t\t))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "AdWorks Net Margin % (YTD)",
            "expression": [
              "CALCULATE([AdWorks Net Margin %],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "AdWorks Net Margin % (CY)",
            "expression": [
              "CALCULATE([AdWorks Net Margin %],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "AdWorks Net Margin % (PYTD)",
            "expression": [
              "CALCULATE([AdWorks Net Margin %],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t\t\t))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "AdWorks Net Margin % (PY)",
            "expression": [
              "CALCULATE([AdWorks Net Margin %],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t'Date'[Calendar Year Month Number] = MAX('Date'[Calendar Year Month Number]) - 12 &&",
              "\t'Date'[Date] >= MIN('Date'[Prior Calendar Year Date]) && 'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Reseller Net Margin % (YTD)",
            "expression": [
              "CALCULATE([Reseller Net Margin %],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Reseller Net Margin % (CY)",
            "expression": [
              "CALCULATE([Reseller Net Margin %],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ],
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "Reseller Net Margin % (PYTD)",
            "expression": [
              "CALCULATE([Reseller Net Margin %],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t\t\t))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Reseller Net Margin % (PY)",
            "expression": [
              "CALCULATE([Reseller Net Margin %],FILTER(ALL('Date'),",
              "\tCONTAINS(VALUES('Date'[Prior Calendar Year Date]),'Date'[Prior Calendar Year Date],'Date'[Date])))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Sales Var to Plan (YTD)",
            "expression": [
              "CALCULATE([Internet Net Sales Var to Plan],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0"
          },
          {
            "name": "Internet Sales Var to Plan (CY)",
            "expression": [
              "CALCULATE([Internet Net Sales Var to Plan],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Var to Plan (PYTD)",
            "expression": [
              "CALCULATE([Internet Net Sales Var to Plan],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t\t\t))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Var to Plan (PY)",
            "expression": [
              "CALCULATE([Internet Net Sales Var to Plan],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t'Date'[Calendar Year Month Number] = MAX('Date'[Calendar Year Month Number]) - 12 &&",
              "\t'Date'[Date] >= MIN('Date'[Prior Calendar Year Date]) && 'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales (YOY)",
            "expression": "[Internet Net Sales (CY)] - [Internet Net Sales (PY)] ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales (YOY %)",
            "expression": "DIVIDE([Internet Net Sales (YOY)],[Internet Net Sales (PY)]) ",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "AdWorks Net Sales (YOY)",
            "expression": "[AdWorks Net Sales (CY)] - [AdWorks Net Sales (PY)] ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Net Sales (YOY %)",
            "expression": "DIVIDE([AdWorks Net Sales (YOY)],[AdWorks Net Sales (PY)]) "
          },
          {
            "name": "Reseller Net Sales (YOY)",
            "expression": "[Reseller Net Sales (CY)] - [Reseller Net Sales (PY)]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Net Sales (YOY %)",
            "expression": "DIVIDE([Reseller Net Sales (YOY)],[Reseller Net Sales (PY)])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "AdWorks Net Margin % (YOY)",
            "expression": "[AdWorks Net Margin % (CY)] - [AdWorks Net Margin % (PY)] "
          },
          {
            "name": "AdWorks Net Margin % (YOY YTD)",
            "expression": "[AdWorks Net Margin % (YTD)] - [AdWorks Net Margin % (PYTD)]",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Sales (YOY YTD)",
            "expression": "[Internet Net Sales (YTD)] - [Internet Net Sales (PYTD)]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales (YOY YTD %)",
            "expression": "DIVIDE([Internet Net Sales (YOY YTD)],[Internet Net Sales (PYTD)])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Sales Customer Count (YOY)",
            "expression": "[Internet Sales Customer Count (CY)] - [Internet Sales Customer Count (PY)]",
            "formatString": "#,0"
          },
          {
            "name": "Internet Sales Customer Count (YOY %)",
            "expression": "DIVIDE([Internet Sales Customer Count (YOY)],[Internet Sales Customer Count (PY)])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Sales Customer Count (YOY YTD %)",
            "expression": "DIVIDE([Internet Sales Customer Count (YOY YTD)],[Internet Sales Customer Count (PYTD)])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "AdWorks Net Sales (YOY YTD)",
            "expression": "[AdWorks Net Sales (YTD)] - [AdWorks Net Sales (PYTD)]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Net Sales (YOY YTD %)",
            "expression": "DIVIDE([AdWorks Net Sales (YOY YTD)],[AdWorks Net Sales (PYTD)])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Sales Customer Count (YOY YTD)",
            "expression": "[Internet Sales Customer Count (YTD)] - [Internet Sales Customer Count (PYTD)]",
            "formatString": "#,0"
          },
          {
            "name": "Internet Sales Var to Plan (YOY)",
            "expression": "[Internet Sales Var to Plan (CY)] - [Internet Sales Var to Plan (PY)]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Net Sales (YOY YTD)",
            "expression": "[Reseller Net Sales (YTD)] - [Reseller Net Sales (PYTD)]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Net Sales (YOY YTD %)",
            "expression": "DIVIDE([Reseller Net Sales (YOY YTD)],[Reseller Net Sales (PYTD)])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Sales Margin % (YOY)",
            "expression": "[Internet Sales Margin % (CY)] - [Internet Net Sales (PY)]",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Sales Margin % (YOY YTD)",
            "expression": "[Internet Sales Margin % (YTD)] - [Internet Sales Margin % (PYTD)]",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Sales Mix % (YTD)",
            "expression": [
              "CALCULATE([Internet Net Sales Mix %],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Sales Mix % (CY)",
            "expression": [
              "CALCULATE([Internet Net Sales Mix %],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Sales Mix % (PY)",
            "expression": [
              "CALCULATE([Internet Net Sales Mix %],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t'Date'[Calendar Year Month Number] = MAX('Date'[Calendar Year Month Number]) - 12 &&",
              "\t'Date'[Date] >= MIN('Date'[Prior Calendar Year Date]) && 'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Sales Mix % (PYTD)",
            "expression": [
              "CALCULATE([Internet Net Sales Mix %],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t\t\t))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Sales Mix (YOY)",
            "expression": "[Internet Net Sales Mix % (CY)] - [Internet Net Sales Mix % (PY)]",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Sales Mix % (YOY YTD)",
            "expression": "[Internet Net Sales (YTD)] - [Internet Net Sales (PYTD)]",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "AdWorks Net Sales CY +30%",
            "expression": "1.3 * [AdWorks Net Sales (CY)] ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Net Sales CY -30%",
            "expression": ".7 * [AdWorks Net Sales (CY)] "
          },
          {
            "name": "Internet Sales Per Customer (YTD)",
            "expression": [
              "CALCULATE([Internet Sales Per Customer],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Per Customer (CY)",
            "expression": [
              "CALCULATE([Internet Sales Per Customer],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Per Customer (PY)",
            "expression": [
              "CALCULATE([Internet Sales Per Customer],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t'Date'[Calendar Year Month Number] = MAX('Date'[Calendar Year Month Number]) - 12 &&",
              "\t'Date'[Date] >= MIN('Date'[Prior Calendar Year Date]) && 'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Per Customer (PYTD)",
            "expression": [
              "CALCULATE([Internet Sales Per Customer],",
              "\t\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) - 1 && ",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t\t\t))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Per Customer (YOY)",
            "expression": "[Internet Sales Per Customer (CY)] - [Internet Sales Per Customer (PY)]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Per Customer (YOY %)",
            "expression": "DIVIDE([Internet Sales Per Customer (YOY)], [Internet Sales Per Customer (PY)])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Sales Count of New Customers (YTD)",
            "expression": [
              "CALCULATE([Internet Sales New Customers],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Reseller Net Sales Mix % (YTD)",
            "expression": [
              "CALCULATE([Reseller Net Sales Mix %],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Reseller Net Sales Mix % (CY)",
            "expression": [
              "CALCULATE([Reseller Net Sales Mix %],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year Status] = \"Current Calendar Year\" && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Reseller Net Sales Mix % (PY)",
            "expression": [
              "CALCULATE([Reseller Net Sales Mix %],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t'Date'[Calendar Year Month Number] = MAX('Date'[Calendar Year Month Number]) - 12 &&",
              "\t'Date'[Date] >= MIN('Date'[Prior Calendar Year Date]) && 'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Reseller Net Sales Mix % (PYTD)",
            "expression": [
              "CALCULATE([Reseller Net Sales Mix %],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])))"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%"
          },
          {
            "name": "Reseller Net Sales Mix % (YOY)",
            "expression": "[Reseller Net Sales Mix % (CY)] - [Reseller Net Sales Mix % (PY)]",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Reseller Net Sales Mix % (YOY YTD)",
            "expression": "[Reseller Net Sales Mix % (YTD)] - [Reseller Net Sales Mix % (PYTD)]",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Sales (CY - Variable)",
            "expression": [
              "",
              "VAR CY = YEAR(TODAY())",
              "RETURN",
              " CALCULATE([Internet Net Sales],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = CY && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ],
            "isHidden": true
          },
          {
            "name": "Internet Net Sales Plan (YTD)",
            "expression": [
              "CALCULATE([Internet Net Sales Plan],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) ",
              "\t\t&& 'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales Plan (CY)",
            "expression": [
              "CALCULATE([Internet Net Sales Plan],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Target: 10 % of YTD Internet Sales Plan",
            "expression": "[Internet Net Sales Plan (YTD)] *.1",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales Plan (YOY)",
            "expression": "[Internet Net Sales Plan (CY)] - [Internet Net Sales (PY)] ",
            "formatString": "#,0"
          },
          {
            "name": "Internet Net Sales Plan (YOY YTD)",
            "expression": "[Internet Net Sales Plan (YTD)] - [Internet Net Sales (PYTD)] ",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00"
          },
          {
            "name": "Internet Net Sales Plan (YOY %)",
            "expression": "DIVIDE([Internet Net Sales Plan (YOY)],[Internet Net Sales (PY)])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Sales Plan (YOY YTD %)",
            "expression": "DIVIDE([Internet Net Sales Plan (YOY YTD)],[Internet Net Sales (PYTD)])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Sales (CY)",
            "expression": [
              "CALCULATE([Internet Net Sales],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales (YTD)",
            "expression": [
              "CALCULATE([Internet Net Sales],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Target: 25% Above Planned YOY Growth",
            "expression": "1.25 * [Internet Net Sales Plan (YOY %)]",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Target: 25% Above Planned YTD Growth",
            "expression": "1.25 * [Internet Net Sales Plan (YOY YTD %)]",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Sales (Trailing 3 Periods)",
            "expression": [
              "CALCULATE([Internet Net Sales],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year Month Number] >= MAX('Date'[Calendar Year Month Number])-2 && 'Date'[Calendar Year Month Number] <= MAX('Date'[Calendar Year Month Number])))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Sales Customer Count Average of Trailing 6",
            "expression": [
              "",
              "VAR LastNonBlankMonth = LASTNONBLANK('Date'[Calendar Year Month Number],[Internet Sales Customer Count])",
              "VAR SixMonthsPrior = LastNonBlankMonth - 6",
              "RETURN",
              "CALCULATE(AVERAGEX(VALUES('Date'[Calendar Year Month Number]),[Internet Sales Customer Count]),FILTER(ALL('Date'),'Date'[Calendar Year Month Number] <= LastNonBlankMonth -1 && 'Date'[Calendar Year Month Number] >=SixMonthsPrior))"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Internet Sales Margin % Average of Trailing 6",
            "expression": [
              "",
              "VAR LastNonBlankMonth = LASTNONBLANK('Date'[Calendar Year Month Number],[Internet Sales Margin %])",
              "VAR SixMonthsPrior = LastNonBlankMonth - 6",
              "RETURN",
              "CALCULATE(AVERAGEX(VALUES('Date'[Calendar Year Month Number]),[Internet Sales Margin %]),FILTER(ALL('Date'),'Date'[Calendar Year Month Number] <= LastNonBlankMonth -1 && 'Date'[Calendar Year Month Number] >=SixMonthsPrior))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Sales Per Customer Average of Trailing 6",
            "expression": [
              "",
              "VAR LastNonBlankMonth = LASTNONBLANK('Date'[Calendar Year Month Number],[Internet Sales Per Customer])",
              "VAR SixMonthsPrior = LastNonBlankMonth - 6",
              "RETURN",
              "CALCULATE(AVERAGEX(VALUES('Date'[Calendar Year Month Number]),[Internet Sales Per Customer]),FILTER(ALL('Date'),'Date'[Calendar Year Month Number] <= LastNonBlankMonth -1 && 'Date'[Calendar Year Month Number] >=SixMonthsPrior))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales (YTD Last Month)",
            "expression": [
              "CALCULATE([Internet Net Sales],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date]) && 'Date'[Calendar Month Number] <= [Prior Calendar Month Number]))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Target: 10 % Above PYTD Internet Customers",
            "expression": "[Internet Sales Customer Count (PYTD)] * 1.1",
            "formatString": "#,0"
          },
          {
            "name": "Target: 50 % Above PYTD Internet Customers",
            "expression": "[Internet Sales Customer Count (PYTD)] * 1.5"
          },
          {
            "name": "Internet Net Sales (CY Test)",
            "expression": [
              "CALCULATE([Internet Net Sales],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year])),VALUES('Date'[Date])",
              "\t\t)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true
          },
          {
            "name": "Internet Net Sales (MTD)",
            "expression": [
              "CALCULATE([Internet Net Sales],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year Month Number] = MAX('Date'[Calendar Year Month Number]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales (WTD)",
            "expression": [
              "CALCULATE([Internet Net Sales],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year Week Number] = MAX('Date'[Calendar Year Week Number]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales (PMTD)",
            "expression": [
              "CALCULATE([Internet Net Sales],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year Month Number] = MAX('Date'[Calendar Year Month Number])-1 && ",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Month Date])",
              "\t\t\t))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales (PWTD)",
            "expression": [
              "CALCULATE([Internet Net Sales],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year Week Number] = MAX('Date'[Calendar Year Week Number])-1 && ",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Week Date])",
              "\t\t\t))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales (PY)",
            "expression": [
              "CALCULATE([Internet Net Sales],FILTER(ALL('Date'),",
              "\tCONTAINS(VALUES('Date'[Prior Calendar Year Date]),'Date'[Prior Calendar Year Date],'Date'[Date])))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "min prior calendar date",
            "expression": "min('Date'[Prior Calendar Year Date])",
            "formatString": "General Date",
            "isHidden": true
          },
          {
            "name": "max prior calendar date",
            "expression": "max('Date'[Prior Calendar Year Date])",
            "formatString": "General Date",
            "isHidden": true
          },
          {
            "name": "Internet Net Sales (Today)",
            "expression": "CALCULATE([Internet Net Sales],FILTER(ALL('Date'),'Date'[Date] = TODAY()))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales (Yesterday)",
            "expression": "CALCULATE([Internet Net Sales],FILTER(ALL('Date'),'Date'[Date] = TODAY()-1))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Margin (CY)",
            "expression": [
              "CALCULATE([Internet Net Margin],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Margin (PY)",
            "expression": [
              "CALCULATE([Internet Net Margin],FILTER(ALL('Date'),",
              "\tCONTAINS(VALUES('Date'[Prior Calendar Year Date]),'Date'[Prior Calendar Year Date],'Date'[Date])))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Margin (YTD)",
            "expression": [
              "CALCULATE([Internet Net Margin],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Margin (PYTD)",
            "expression": [
              "CALCULATE([Internet Net Margin],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t\t\t))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Margin (YOY)",
            "expression": "[Internet Net Margin (CY)] - [Internet Net Margin (PY)] ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Margin (YOY YTD)",
            "expression": "[Internet Net Margin (YTD)] - [Internet Net Margin (PYTD)]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Margin (YOY %)",
            "expression": "DIVIDE([Internet Net Margin (YOY)],[Internet Net Margin (PY)]) ",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Margin (YOY YTD %)",
            "expression": "DIVIDE([Internet Net Margin (YOY YTD)],[Internet Net Margin (PYTD)])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Sales (Trailing 60 Days)",
            "expression": [
              "",
              "VAR MaxDate = MAX('Date'[Date])",
              "VAR StartDate = MaxDate - 59",
              "RETURN",
              "CALCULATE([Internet Net Sales],FILTER(ALL('Date'),'Date'[Date] >= StartDate && 'Date'[Date] <= MaxDate))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales Trailing (60 to 120 Days)",
            "expression": [
              "",
              "VAR MaxDate = MAX('Date'[Date])",
              "VAR EndDate = MaxDate - 60",
              "VAR StartDate = EndDate - 59",
              "RETURN",
              "CALCULATE([Internet Net Sales],FILTER(ALL('Date'), 'Date'[Date] >= StartDate && 'Date'[Date] <= EndDate))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales (YTD Last Week)",
            "expression": [
              "CALCULATE([Internet Net Sales],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date]) && 'Date'[Calendar Week Number in Year] <= [Prior Calendar Week Number]))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Margin % (CY)",
            "expression": [
              "CALCULATE([Internet Net Margin %],FILTER(ALL('Date'),",
              "\t'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t'Date'[Date] >= MIN('Date'[Date]) &&",
              "\t'Date'[Date] <= MAX('Date'[Date]))",
              "\t)"
            ]
          },
          {
            "name": "Internet Net Margin % (PY)",
            "expression": [
              "CALCULATE([Internet Net Margin %],FILTER(ALL('Date'),",
              "\tCONTAINS(VALUES('Date'[Prior Calendar Year Date]),'Date'[Prior Calendar Year Date],'Date'[Date])))"
            ]
          },
          {
            "name": "Internet Net Margin % (PYTD)",
            "expression": [
              "CALCULATE([Internet Net Margin %],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year])-1 && ",
              "\t\t\t'Date'[Date] <= MAX('Date'[Prior Calendar Year Date])",
              "\t\t\t))"
            ]
          },
          {
            "name": "Internet Net Margin % (YOY)",
            "expression": "[Internet Net Margin % (CY)] - [Internet Net Margin % (PY)]"
          },
          {
            "name": "Internet Net Margin % (YTD)",
            "expression": [
              "CALCULATE([Internet Net Margin %],",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Date] <= MAX('Date'[Date])))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Margin % (YOY YTD %)",
            "expression": "[Internet Net Margin % (YTD)] - [Internet Net Margin % (PYTD)]"
          },
          {
            "name": "Reseller Net Margin % (YOY)",
            "expression": "[Reseller Net Margin % (CY)] - [Reseller Net Margin % (PY)]"
          },
          {
            "name": "Reseller Net Margin % (YOY YTD %)",
            "expression": "[Reseller Net Margin % (YTD)] - [Reseller Net Margin % (PYTD)]"
          },
          {
            "name": "AdWorks Net Sales Plan (YTD)",
            "expression": [
              "",
              "IF([Plan Grain Status] = \"Actual Grain\",BLANK(),",
              "CALCULATE(sum('Sales and Margin Plan'[Internet Net Sales]) + sum('Sales and Margin Plan'[Reseller Net Sales]),",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Calendar Year Month Number] <= MAX('Date'[Calendar Year Month Number]))))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Net Margin Plan % (YTD)",
            "expression": [
              "",
              "CALCULATE(DIVIDE(sum('Sales and Margin Plan'[Internet Margin $]) + sum('Sales and Margin Plan'[Reseller Margin $]),sum('Sales and Margin Plan'[Internet Net Sales]) + sum('Sales and Margin Plan'[Reseller Net Sales])),",
              "\tFILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && ",
              "\t\t'Date'[Calendar Year Month Number] <= MAX('Date'[Calendar Year Month Number])))"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "12f65def-b791-4b84-b5b0-ad016ec71dc8"
          },
          {
            "name": "LinkedQueryName",
            "value": "Date Intelligence Metrics"
          }
        ]
      },
      {
        "name": "Adventure Works Sales",
        "description": "A collection of measures which combine both internet and reseller sales.",
        "columns": [
          {
            "name": "Dummy",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Dummy",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Adventure Works Sales-d21609e9-aebe-4c24-bf52-1aa0c87c7a31",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=#\"Adventure Works Sales\"",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "AdWorks Net Sales",
            "description": "Internet Net Sales plus Reseller Net Sales.",
            "expression": "[Internet Net Sales] + [Reseller Net Sales] ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales Mix %",
            "expression": "DIVIDE([Internet Net Sales],[AdWorks Net Sales]) ",
            "formatString": "0%;-0%;0%"
          },
          {
            "name": "Reseller Net Sales Mix %",
            "expression": "DIVIDE([Reseller Net Sales],[AdWorks Net Sales]) "
          },
          {
            "name": "AdWorks Net Margin",
            "description": "AdWorks Net Sales minus AdWorks Cost of Sales.",
            "expression": "[AdWorks Net Sales] - [AdWorks Cost of Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Net Margin %",
            "description": "AdWorks Net Margin divided by AdWorks Net Sales.",
            "expression": "DIVIDE([AdWorks Net Margin],[AdWorks Net Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Product Total Net Sales Rank (YOY YTD %)",
            "expression": "if(or(ISBLANK([AdWorks Net Sales (YOY YTD %)]),[AdWorks Net Sales (YOY YTD %)]=-1),BLANK(),RANKX(ALL('Product'[Product Alternate Key],'Product'[Product Name]),[AdWorks Net Sales (YOY YTD %)],,DESC,Skip))",
            "formatString": "#,0"
          },
          {
            "name": "Product Total Net Sales Rank ASC (YOY YTD %)",
            "expression": "if(OR(ISBLANK([AdWorks Net Sales (YOY YTD %)]),[AdWorks Net Sales (YOY YTD %)]=-1),BLANK(),RANKX(ALL('Product'[Product Alternate Key],'Product'[Product Name]),[AdWorks Net Sales (YOY YTD %)],,ASC,Skip))",
            "formatString": "#,0"
          },
          {
            "name": "Product Total Sales Rank (PYTD)",
            "expression": [
              "",
              "IF(HASONEVALUE('Product'[Product Alternate Key]),",
              "RANKX(ALL('Product'[Product Name],'Product'[Product Alternate Key]),[AdWorks Net Sales (PYTD)],,DESC,Skip),BLANK())"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Last Refresh Message",
            "expression": "\"Last Refreshed: \" & [LastRefreshMeasure]",
            "isHidden": true
          },
          {
            "name": "Last Refresh Msg",
            "expression": [
              "",
              "\tVAR CurrentDateValue = MAX('CurrentDate'[CurrentDate])",
              "\tRETURN",
              "\t\t\"Last Refreshed: \" & CurrentDateValue"
            ]
          },
          {
            "name": "LastRefreshMeasure",
            "expression": "MAX(CurrentDate[CurrentDate])",
            "isHidden": true
          },
          {
            "name": "AdWorks Cost of Sales",
            "description": "Internet Cost of Sales plus Reseller Cost of Sales.",
            "expression": "[Internet Cost of Sales] + [Reseller Cost of Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Gross Sales",
            "description": "Internet Gross Sales plus Reseller Gross Sales.",
            "expression": "[Internet Gross Sales] + [Reseller Gross Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Sales Product Cost",
            "description": "Internet Sales Product Cost plus Reseller Sales Product Cost.",
            "expression": "[Internet Sales Product Cost] + [Reseller Sales Product Cost]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Freight Costs",
            "expression": "[Internet Sales Freight Cost] + [Reseller Sales Freight Cost]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Discounts",
            "description": "Total corporate sales discounts (online and reseller).",
            "expression": "[Internet Sales Discounts] + [Reseller Sales Discounts]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Gross Margin",
            "description": "AdWorks Gross Sales minus AdWorks Cost of Sales.",
            "expression": "[AdWorks Gross Sales] - [AdWorks Cost of Sales]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Gross Margin %",
            "description": "AdWorks Gross Margin divided by AdWorks Gross Sales.",
            "expression": "DIVIDE([AdWorks Gross Margin],[AdWorks Gross Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "AdWorks Gross Product Margin",
            "description": "AdWorks Gross Sales minus AdWorks Sales Product Cost.",
            "expression": "[AdWorks Gross Sales] - [AdWorks Sales Product Cost]",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############"
          },
          {
            "name": "AdWorks Gross Product Margin %",
            "description": "AdWorks Gross Product Margin divided by AdWorks Gross Sales.",
            "expression": "DIVIDE([AdWorks Gross Product Margin],[AdWorks Gross Sales])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "AdWorks Net Product Margin",
            "description": "AdWorks Net Sales minus AdWorks Sales Product Cost.",
            "expression": "[AdWorks Net Sales] - [AdWorks Sales Product Cost]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00"
          },
          {
            "name": "AdWorks Net Product Margin %",
            "description": "AdWorks Net Product Margin divided by AdWorks Net Sales.",
            "expression": "DIVIDE([AdWorks Net Product Margin],[AdWorks Net Sales])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Brett Divide",
            "expression": [
              "",
              "VAR num = 7 Var denom = BLANK()",
              "RETURN",
              "num/denom"
            ],
            "isHidden": true
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8e96d8f8-0a1d-44a9-b808-a2af7a97d700"
          },
          {
            "name": "LinkedQueryName",
            "value": "Adventure Works Sales"
          }
        ]
      },
      {
        "name": "CurrentDate",
        "isHidden": true,
        "columns": [
          {
            "name": "CurrentDate",
            "dataType": "dateTime",
            "sourceColumn": "CurrentDate",
            "formatString": "m/d/yyyy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeGeneralPattern\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "DateTime#####Date"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "CurrentDate"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CurrentDate-eda24406-fca6-455e-bc44-0d71f4de0361",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=CurrentDate",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bbf10d06-2366-40d8-9b27-44d40802d6ac"
          },
          {
            "name": "LinkedQueryName",
            "value": "CurrentDate"
          }
        ]
      },
      {
        "name": "BridgeSalesTerritoryRegion",
        "isHidden": true,
        "columns": [
          {
            "name": "Sales Territory Region",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sales Territory Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Sales Territory Region"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "BridgeSalesTerritoryRegion-80fa7fe5-958f-4e54-9000-1d4b3d180bad",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=BridgeSalesTerritoryRegion",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "257efb82-4e04-416a-99de-5da883afe7c0"
          },
          {
            "name": "LinkedQueryName",
            "value": "BridgeSalesTerritoryRegion"
          }
        ]
      },
      {
        "name": "Sales and Margin Plan",
        "description": "The global Adventure Works Sales and Margin Plan.",
        "columns": [
          {
            "name": "Calendar Yr-Mo",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Calendar Yr-Mo",
            "sortByColumn": "Calendar Yr-Mo Sort",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Calendar Yr-Mo"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Sales Territory Region",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sales Territory Region",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Sales Territory Region"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Product Subcategory",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Subcategory",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"Text\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "String#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Product Subcategory"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Internet Net Sales",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Internet Net Sales",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyGeneral\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Internet Net Sales"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Internet Net Sales Margin %",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Internet Net Sales Margin %",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Internet Net Sales Margin %"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Reseller Net Sales",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Reseller Net Sales",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyGeneral\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Reseller Net Sales"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Reseller Net Sales Margin %",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Reseller Net Sales Margin %",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"General\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Double#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Reseller Net Sales Margin %"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Internet Margin $",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Internet Margin $",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyGeneral\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Internet Margin $"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Reseller Margin $",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Reseller Margin $",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyGeneral\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Decimal#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Reseller Margin $"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Year",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Year"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          },
          {
            "name": "Calendar Yr-Mo Sort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Calendar Yr-Mo Sort",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Calendar Yr-Mo Sort"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sales and Margin Plan-a041788a-207d-456c-897e-3ffaa2675d33",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=#\"Sales and Margin Plan\"",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Internet Net Sales Plan",
            "expression": [
              "",
              "if([Plan Grain Status] = \"Actual Grain\",BLANK(),",
              " SUM('Sales and Margin Plan'[Internet Net Sales]))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Sales and Margin Plan Rows",
            "expression": "COUNTROWS('Sales and Margin Plan')",
            "formatString": "#,0"
          },
          {
            "name": "Reseller Net Sales Plan",
            "expression": [
              "",
              "IF([Plan Grain Status] = \"Actual Grain\",BLANK(),",
              "SUM('Sales and Margin Plan'[Reseller Net Sales]))"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Net Sales Plan",
            "expression": "[Internet Net Sales Plan] + [Reseller Net Sales Plan] ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Net Margin Plan",
            "expression": "SUM('Sales and Margin Plan'[Reseller Margin $]) ",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Margin Plan",
            "expression": "SUM('Sales and Margin Plan'[Internet Margin $])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "AdWorks Net Margin Plan",
            "expression": "[Internet Net Margin Plan] + [Reseller Net Margin Plan]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Margin % Plan",
            "expression": "DIVIDE([Internet Net Margin Plan],[Internet Net Sales Plan])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Reseller Net Margin % Plan",
            "expression": "DIVIDE([Reseller Net Margin Plan],[Reseller Net Sales Plan])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "AdWorks Net Margin Plan %",
            "expression": "DIVIDE([AdWorks Net Margin Plan],[AdWorks Net Sales Plan])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Internet Net Sales Var to Plan",
            "expression": [
              "",
              "IF([Plan Grain Status] = \"Actual Grain\",BLANK(),",
              "[Internet Net Sales] - [Internet Net Sales Plan])"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Reseller Net Sales Var to Plan",
            "expression": [
              "",
              "IF([Plan Grain Status] = \"Actual Grain\", BLANK(),",
              "[Reseller Net Sales] - [Reseller Net Sales Plan])"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales Margin % Var to Plan",
            "expression": "[Internet Sales Margin %] - [Internet Net Margin % Plan]",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "AdWorks Net Sales Var to Plan",
            "expression": "[AdWorks Net Sales] - [AdWorks Net Sales Plan]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0"
          },
          {
            "name": "Internet Net Sales Var to Plan %",
            "expression": "DIVIDE([Internet Net Sales Var to Plan],[Internet Net Sales Plan])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Reseller Net Sales Var to Plan %",
            "expression": "DIVIDE([Reseller Net Sales Var to Plan],[Reseller Net Sales Plan])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "AdWorks Net Sales Var to Plan %",
            "expression": "DIVIDE([AdWorks Net Sales Var to Plan],[AdWorks Net Sales Plan])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "YTD internet sales plan",
            "expression": "CALCULATE(sum('Sales and Margin Plan'[Internet Net Sales]),FILTER(ALL('Date'),'Date'[Calendar Year] = MAX('Date'[Calendar Year]) && 'Date'[Calendar Year Month Number] <= MAX('Date'[Calendar Year Month Number])))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "65adc0ab-9b81-48fe-a511-e4ae6b206607"
          },
          {
            "name": "LinkedQueryName",
            "value": "Sales and Margin Plan"
          }
        ]
      },
      {
        "name": "Measure Support",
        "isHidden": true,
        "columns": [
          {
            "name": "Dummy",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Dummy",
            "formatString": "0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "Format",
                "value": "<Format Format=\"NumberWhole\" Accuracy=\"0\" />"
              },
              {
                "name": "DataTypeAtRefresh",
                "value": "Int64#####not a type"
              },
              {
                "name": "PBI_NameAtRefresh",
                "value": "Dummy"
              },
              {
                "name": "PBI_WasHiddenAtRefresh",
                "value": "False"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Measure Support-68ea30dc-6cf3-4e58-9fd3-7a5ea235bdbd",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source=#\"Measure Support\"",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sales Territory Table Filter Check",
            "expression": "ISCROSSFILTERED('Sales Territory')",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true
          },
          {
            "name": "Current User",
            "expression": "USERPRINCIPALNAME()",
            "isHidden": true
          },
          {
            "name": "Product Subcat Filter Check",
            "expression": "ISFILTERED('Product'[Product Subcategory]) ",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true
          },
          {
            "name": "Current Year",
            "expression": "LOOKUPVALUE('Date'[Calendar Year],'Date'[Date],TODAY())",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Date Grain Plan Filter Test",
            "expression": [
              "SWITCH(",
              "\tTRUE(),",
              "\tNOT(ISCROSSFILTERED('Date')),\"Plan Grain\",",
              "\tISFILTERED('Date'[Calendar Week in Year]) || ISFILTERED('Date'[Date]) || ISFILTERED('Date'[Weekday]) ||ISFILTERED('Date'[Calendar Yr-Wk]), \"Actual Grain\",",
              "\"Plan Grain\"",
              ")",
              "\t "
            ],
            "isHidden": true
          },
          {
            "name": "Product Grain Plan Filter Test",
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "\tNOT(ISCROSSFILTERED('Product')),\"Plan Grain\", ",
              "\tISFILTERED('Product'[Product Alternate Key]) || ISFILTERED('Product'[Product Line]) || ISFILTERED('Product'[Product Model]) || ISFILTERED('Product'[Product Name]) || ISFILTERED('Product'[Product Color]) || ISFILTERED('Product'[Product Style]), \"Actual Grain\",",
              "\t\"Plan Grain\")"
            ],
            "isHidden": true
          },
          {
            "name": "Sales Territory Grain Plan Filter Test",
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "\tNOT(ISCROSSFILTERED('Sales Territory')),\"Plan Grain\", ",
              "\tISFILTERED('Sales Territory'[Sales Territory Key]), \"Actual Grain\",",
              "\t\"Plan Grain\")"
            ],
            "isHidden": true
          },
          {
            "name": "Plan Grain Status",
            "expression": [
              "",
              "IF([Date Grain Plan Filter Test] = \"Plan Grain\" && [Product Grain Plan Filter Test] = \"Plan Grain\" && [Sales Territory Grain Plan Filter Test] = \"Plan Grain\", ",
              "\t\t\"Plan Grain\",",
              "\t\t\"Actual Grain\")"
            ],
            "isHidden": true
          },
          {
            "name": "Prior Calendar Month Number",
            "expression": "LOOKUPVALUE('Date'[Calendar Month Number],'Date'[Date],TODAY())-1",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "VariablePlaying",
            "expression": [
              "",
              "VAR Brett = \"Something\"",
              "VAR MyRate = .25",
              "RETURN",
              "MyRate",
              ""
            ],
            "isHidden": true
          },
          {
            "name": "Last Completed Calendar Month Number (New)",
            "expression": "MONTH(TODAY()) - 1",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Internet Sales Cross Filtered",
            "expression": "ISCROSSFILTERED('Internet Sales')",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true
          },
          {
            "name": "Product Category Filtered",
            "expression": "ISFILTERED('Product'[Product Category])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true
          },
          {
            "name": "Product Category CrossFiltered",
            "expression": "ISCROSSFILTERED('Product'[Product Category])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true
          },
          {
            "name": "First Day of Current Year",
            "expression": [
              "",
              "VAR CY = YEAR(TODAY())",
              "RETURN",
              "CALCULATE(FIRSTDATE('Date'[Date]),FILTER(ALL('Date'),'Date'[Calendar Year] = CY))"
            ],
            "formatString": "m/d/yyyy",
            "isHidden": true
          },
          {
            "name": "Current Month Number",
            "expression": "MONTH(MAX(CurrentDate[CurrentDate]))",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Target: 10% Above PYTD Internet Sales",
            "expression": [
              "",
              "[Internet Net Sales (PYTD)] * 1.10"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true
          },
          {
            "name": "MysubcatValuecheck",
            "expression": "HASONEVALUE('Product'[Product Subcategory])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true
          },
          {
            "name": "Prior Calendar Week Number",
            "expression": "LOOKUPVALUE('Date'[Calendar Week Number in Year],'Date'[Date],TODAY())-1",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Internet Net Sales vs Plan Index",
            "expression": "IF([Internet Net Sales Var to Plan %] > 0,1,2)",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Reseller Net Sales vs Plan Index",
            "expression": "IF([Reseller Net Sales Var to Plan %] > 0,1,2)",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "AdWorks Net Sales vs Plan Index",
            "expression": "IF([AdWorks Net Sales Var to Plan %] > 0,1,2)",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "Internet Gross Product Margin Description",
            "expression": "\"Internet Gross Sales minus Internet Sales Product Cost\"",
            "isHidden": true
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6d035794-7376-4eae-8902-228961916175"
          },
          {
            "name": "LinkedQueryName",
            "value": "Measure Support"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "4ae5a333-7e79-4dbf-a8a8-2cd20fd76278",
        "fromTable": "Internet Sales",
        "fromColumn": "Order Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "065c8570-50ad-4ed8-a179-e1b764a0debb",
        "fromTable": "Reseller Sales",
        "fromColumn": "Order Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "5b99aed8-4aac-4e07-8050-89b5360f14f3",
        "fromTable": "Date",
        "fromColumn": "Calendar Yr-Mo",
        "toTable": "BridgeBudgetDate",
        "toColumn": "Calendar Yr-Mo",
        "crossFilteringBehavior": "bothDirections",
        "securityFilteringBehavior": "bothDirections"
      },
      {
        "name": "4cdd298d-98b0-43b7-beee-892d49112dc0",
        "fromTable": "Product",
        "fromColumn": "Product Subcategory",
        "toTable": "BridgeProductSubCat",
        "toColumn": "Product Subcategory",
        "crossFilteringBehavior": "bothDirections",
        "securityFilteringBehavior": "bothDirections"
      },
      {
        "name": "498da80c-c754-4fbb-a96e-a88b56fd5b3a",
        "fromTable": "Sales and Margin Plan",
        "fromColumn": "Calendar Yr-Mo",
        "toTable": "BridgeBudgetDate",
        "toColumn": "Calendar Yr-Mo"
      },
      {
        "name": "dd3dbb14-0efa-4b32-91f4-730e42a2118f",
        "fromTable": "Sales and Margin Plan",
        "fromColumn": "Product Subcategory",
        "toTable": "BridgeProductSubCat",
        "toColumn": "Product Subcategory"
      },
      {
        "name": "8fea30bf-bcc4-4c98-80b2-dfb1ba20795e",
        "fromTable": "Sales Territory",
        "fromColumn": "Sales Territory Region",
        "toTable": "BridgeSalesTerritoryRegion",
        "toColumn": "Sales Territory Region",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "00102a78-935c-4d1d-aa43-dc2be037e02e",
        "fromTable": "Sales and Margin Plan",
        "fromColumn": "Sales Territory Region",
        "toTable": "BridgeSalesTerritoryRegion",
        "toColumn": "Sales Territory Region"
      },
      {
        "name": "b2d95188-5817-46e2-a2a1-39589dd3477f",
        "fromTable": "Internet Sales",
        "fromColumn": "Customer Key",
        "toTable": "Customer",
        "toColumn": "Customer Key"
      },
      {
        "name": "b014ec97-44e6-44f5-920a-00ced62fd24c",
        "fromTable": "Internet Sales",
        "fromColumn": "Product Key",
        "toTable": "Product",
        "toColumn": "Product Key"
      },
      {
        "name": "18ec90e1-d1bd-4370-b8a7-4baaa024a7d5",
        "fromTable": "Internet Sales",
        "fromColumn": "Promotion Key",
        "toTable": "Promotion",
        "toColumn": "Promotion Key"
      },
      {
        "name": "e1903781-84a6-4ba6-b457-efea7d3c00e6",
        "fromTable": "Internet Sales",
        "fromColumn": "Sales Territory Key",
        "toTable": "Sales Territory",
        "toColumn": "Sales Territory Key"
      },
      {
        "name": "88b2d52c-7ae1-42d9-89bc-f6560106d25b",
        "fromTable": "Reseller Sales",
        "fromColumn": "Currency Key",
        "toTable": "Currency",
        "toColumn": "Currency Key"
      },
      {
        "name": "e2dd0746-98be-4aaa-8d03-7deed0f87c8a",
        "fromTable": "Reseller Sales",
        "fromColumn": "Promotion Key",
        "toTable": "Promotion",
        "toColumn": "Promotion Key"
      },
      {
        "name": "8484e9b8-f186-448e-b7ac-a92dcf021183",
        "fromTable": "Reseller Sales",
        "fromColumn": "Employee Key",
        "toTable": "Employee",
        "toColumn": "Employee Key"
      },
      {
        "name": "fb617d85-1210-4012-994d-47eaff538b34",
        "fromTable": "Reseller Sales",
        "fromColumn": "Sales Territory Key",
        "toTable": "Sales Territory",
        "toColumn": "Sales Territory Key"
      },
      {
        "name": "8f0c0094-c0b6-42ef-afe8-e3a3b9c6846d",
        "fromTable": "Reseller Sales",
        "fromColumn": "Product Key",
        "toTable": "Product",
        "toColumn": "Product Key"
      },
      {
        "name": "dd69e1e3-840a-4fc1-9b09-cdba200e0ce7",
        "fromTable": "Internet Sales",
        "fromColumn": "Currency Key",
        "toTable": "Currency",
        "toColumn": "Currency Key"
      },
      {
        "name": "c3a3503e-345f-4a08-8ed2-0863d99ac9ed",
        "fromTable": "Reseller Sales",
        "fromColumn": "Reseller Key",
        "toTable": "Reseller",
        "toColumn": "Reseller Key"
      },
      {
        "name": "82fc7c9b-679c-428b-8d70-94724e7b6667",
        "fromTable": "Internet Sales",
        "fromColumn": "Due Date",
        "toTable": "Date",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "2ce27568-3fe3-4a47-9682-f9eaa0ba8614",
        "fromTable": "Internet Sales",
        "fromColumn": "Ship Date",
        "toTable": "Date",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "b36560f6-3d97-4eb7-9991-71837693a8e0",
        "fromTable": "Reseller Sales",
        "fromColumn": "Due Date",
        "toTable": "Date",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "cf87331a-d5ae-4f26-b16a-4e26912f6439",
        "fromTable": "Reseller Sales",
        "fromColumn": "Ship Date",
        "toTable": "Date",
        "toColumn": "Date",
        "isActive": false
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "roles": [
      {
        "name": "North America Sales Group",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Sales Territory",
            "filterExpression": "[Sales Territory Group] = \"North America\""
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "afb05827039a4a36b06e57282741cd1a"
          }
        ]
      },
      {
        "name": "Pacific Sales Group",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Sales Territory",
            "filterExpression": "[Sales Territory Group] = \"Pacific\""
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1c679e4f0124426c86ff44247a487265"
          }
        ]
      },
      {
        "name": "Europe Sales Group",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Sales Territory",
            "filterExpression": "[Sales Territory Group] = \"Europe\""
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "dd013d481f6c423bbe941bd86ac4e8d3"
          }
        ]
      },
      {
        "name": "Executives",
        "modelPermission": "read",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a632fd4ed8d74e8e9601184999b85967"
          }
        ]
      }
    ],
    "expressions": [
      {
        "name": "ProdServer",
        "kind": "m",
        "expression": "\"ATLAS\" meta [IsParameterQuery=true, List={\"ATLAS\", \"BATON\", \"SIREN\"}, DefaultValue=\"ATLAS\", Type=\"Text\", IsParameterQueryRequired=true]"
      },
      {
        "name": "ProdDB",
        "kind": "m",
        "expression": "\"AdventureWorksDW\" meta [IsParameterQuery=true, List={\"AdventureWorksDW\", \"AdventureWorks\"}, DefaultValue=\"AdventureWorksDW\", Type=\"Text\", IsParameterQueryRequired=true]"
      },
      {
        "name": "AdWorksSQLServer",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Sql.Database(ProdServer,ProdDB)",
          "in",
          "    Source"
        ]
      },
      {
        "name": "Measure Support",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Value.NativeQuery(AdWorksSQLServer, \"Select null as Dummy\"),",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(Source, [DefaultColumnName = \"Measure Support\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "Adventure Works Sales",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Value.NativeQuery(AdWorksSQLServer, \"Select null as Dummy\"),",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(Source, [DefaultColumnName = \"Adventure Works Sales\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "Date Intelligence Metrics",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Value.NativeQuery(AdWorksSQLServer, \"Select null as Dummy\"),",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(Source, [DefaultColumnName = \"Date Intelligence Metrics\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "Internet Sales",
        "kind": "m",
        "expression": [
          "let",
          "    Source = AdWorksSQLServer,",
          "    ISales = Source{[Schema = \"BI\", Item = \"vFact_InternetSales\"]}[Data],",
          "    RemoveCols = Table.RemoveColumns(ISales,",
          "        {\"Order Date Key\", \"Ship Date Key\", \"Due Date Key\",",
          "        \"Extended Amount\", \"Sales Amount\", \"Total Product Cost\"",
          "        }),",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(RemoveCols, [DefaultColumnName = \"Internet Sales\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "Reseller Sales",
        "kind": "m",
        "expression": [
          "let",
          "    Source = AdWorksSQLServer,",
          "    ResellerSales = Source{[Schema = \"BI\", Item = \"vFact_ResellerSales\"]}[Data],",
          "    RemoveColumns = Table.RemoveColumns(ResellerSales,",
          "            {\"Due Date Key\", \"Order Date Key\", \"Ship Date Key\", ",
          "            \"Extended Amount\", \"Total Product Cost\", \"Sales Amount\"}),",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(RemoveColumns, [DefaultColumnName = \"Reseller Sales\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "Sales and Margin Plan",
        "kind": "m",
        "expression": [
          "let",
          "    Workbook = Excel.Workbook(#\"File/C:\\Users\\Brett Powell\\SampleDataSources\\AdWorks Sales Plan xlsx\"),",
          "    PlanTbl = Workbook{[Item=\"PlanTbl\",Kind=\"Table\"]}[Data],",
          "    DataTypes = Table.TransformColumnTypes(PlanTbl,",
          "            {",
          "                {\"Calendar Yr-Mo\", type text},",
          "                {\"Calendar Yr-Mo Sort\", Int64.Type},",
          "                {\"Year\", Int64.Type},",
          "                {\"Sales Territory Region\", type text},",
          "                {\"Product Subcategory\", type text},",
          "                {\"Internet Net Sales\", Currency.Type},",
          "                {\"Internet Net Sales Margin %\", type number},",
          "                {\"Reseller Net Sales\", Currency.Type},",
          "                {\"Reseller Net Sales Margin %\", type number},",
          "                {\"Internet Margin $\", Currency.Type},",
          "                {\"Reseller Margin $\", Currency.Type}",
          "            }",
          "                                        ),",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(DataTypes, [DefaultColumnName = \"Sales and Margin Plan\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "SalesPlanDirectory",
        "kind": "m",
        "expression": "\"C:\\Users\\Brett Powell\\SampleDataSources\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
      },
      {
        "name": "SalesPlanFile",
        "kind": "m",
        "expression": "\"AdWorks Sales Plan\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
      },
      {
        "name": "SalesPlanFilePath",
        "kind": "m",
        "expression": [
          "let",
          "    FilePath = SalesPlanDirectory & \"\\\" & SalesPlanFile & \".xlsx\"",
          "in",
          "    FilePath"
        ]
      },
      {
        "name": "Currency",
        "kind": "m",
        "expression": [
          "let",
          "    Source = AdWorksSQLServer,",
          "    Currency = Source{[Schema = \"BI\", Item = \"vDim_Currency\"]}[Data],",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(Currency, [DefaultColumnName = \"Currency\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "Customer",
        "kind": "m",
        "expression": [
          "let",
          "// Customer History Date Bands",
          "",
          "   CurrentDate = DateTime.Date(DateTime.LocalNow()),",
          "   OneYearAgo = Date.AddYears(CurrentDate,-1),",
          "   TwoYearsAgo = Date.AddYears(CurrentDate,-2),",
          "   ThreeYearsAgo = Date.AddYears(CurrentDate,-3),",
          "",
          "//Customer Dimension View",
          "",
          "    Source = AdWorksSQLServer,",
          "    Customer = Source{[Schema = \"BI\", Item = \"vDim_Customer\"]}[Data],",
          "",
          "//Customer History Segment Column",
          "",
          "    CustomerHistoryColumn = Table.AddColumn(Customer, \"Customer History Segment\", each",
          "    if [Customer First Purchase Date] >= OneYearAgo then \"First Year Customer\" ",
          "    else if [Customer First Purchase Date] >= TwoYearsAgo and [Customer First Purchase Date] < OneYearAgo then \"Second Year Customer\"",
          "    else if [Customer First Purchase Date] >= ThreeYearsAgo and [Customer First Purchase Date] < TwoYearsAgo then \"Third Year Customer\" ",
          "else \"Legacy Customer\", type text),",
          "   ",
          "//Customer History Segment Column Sort",
          " ",
          "    CustomerHistColSort = Table.AddColumn(CustomerHistoryColumn, \"Customer History Segment Sort\", each ",
          "    if [Customer First Purchase Date] >= OneYearAgo then 1 ",
          "    else if [Customer First Purchase Date] >= TwoYearsAgo and [Customer First Purchase Date] < OneYearAgo then 2",
          "    else if [Customer First Purchase Date] >= ThreeYearsAgo and [Customer First Purchase Date] < TwoYearsAgo then 3 ",
          "    else 4, Int64.Type),",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(CustomerHistColSort, [DefaultColumnName = \"Customer\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "Date",
        "kind": "m",
        "expression": [
          "let",
          "    Source = AdWorksSQLServer,",
          "    FinDate = Source{[Schema = \"BI\", Item = \"vDim_FinDate\"]}[Data],",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(FinDate, [DefaultColumnName = \"Date\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "Employee",
        "kind": "m",
        "expression": [
          "let",
          "    Source = AdWorksSQLServer,",
          "    Employee = Source{[Schema = \"BI\", Item = \"vDim_Employee\"]}[Data],",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(Employee, [DefaultColumnName = \"Employee\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "Product",
        "kind": "m",
        "expression": [
          "let",
          "    Source = AdWorksSQLServer,",
          "    Product = Source{[Schema = \"BI\", Item = \"vDim_Product\"]}[Data],",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(Product, [DefaultColumnName = \"Product\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "Promotion",
        "kind": "m",
        "expression": [
          "let",
          "    Source = AdWorksSQLServer,",
          "    Promotion = Source{[Schema = \"BI\", Item = \"vDim_Promotion\"]}[Data],",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(Promotion, [DefaultColumnName = \"Promotion\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "Reseller",
        "kind": "m",
        "expression": [
          "let",
          "    Source = AdWorksSQLServer,",
          "    Scenario = Source{[Schema = \"BI\", Item = \"vDim_Reseller\"]}[Data],",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(Scenario, [DefaultColumnName = \"Reseller\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "Sales Territory",
        "kind": "m",
        "expression": [
          "let",
          "    Source = AdWorksSQLServer,",
          "    Territory = Source{[Schema = \"BI\", Item = \"vDim_SalesTerritory\"]}[Data],",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(Territory, [DefaultColumnName = \"Sales Territory\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "BridgeSalesTerritoryRegion",
        "kind": "m",
        "expression": [
          "let",
          "    Regions = Table.SelectColumns(#\"Sales Territory\", \"Sales Territory Region\"),",
          "    DistinctRegions = Table.Distinct(Regions),",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(DistinctRegions, [DefaultColumnName = \"BridgeSalesTerritoryRegion\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "BridgeBudgetDate",
        "kind": "m",
        "expression": [
          "let",
          "    YearMonthColumn = Table.SelectColumns(Date,{\"Calendar Yr-Mo\"}),",
          "    DistinctYearMo = Table.Distinct(YearMonthColumn),",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(DistinctYearMo, [DefaultColumnName = \"BridgeBudgetDate\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "BridgeProductSubCat",
        "kind": "m",
        "expression": [
          "let",
          "    SubCats = Table.SelectColumns(Product, {\"Product Subcategory\"}),",
          "    DistinctSubCats = Table.Distinct(SubCats),",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(DistinctSubCats, [DefaultColumnName = \"BridgeProductSubCat\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in    ",
          "    AutoRemovedColumns1"
        ]
      },
      {
        "name": "CurrentDate",
        "kind": "m",
        "expression": [
          "let",
          "    RefreshDateTime = DateTime.LocalNow(),",
          "    TimeZoneOffset = -5,",
          "    RefreshDateTimeAdjusted = RefreshDateTime + #duration(0,TimeZoneOffset,0,0),",
          "    RefreshDateAdjusted = DateTime.Date(RefreshDateTimeAdjusted),",
          "    TableCreate = Table.FromRecords({[CurrentDate = RefreshDateAdjusted]}),",
          "    DateType = Table.TransformColumnTypes(TableCreate,{\"CurrentDate\", type date}),",
          "    AutoRemovedColumns1 = ",
          "    let",
          "        t = Table.FromValue(DateType, [DefaultColumnName = \"CurrentDate\"]),",
          "        removed = Table.RemoveColumns(t, Table.ColumnsOfType(t, {type table, type record, type list}))",
          "    in",
          "        Table.TransformColumnNames(removed, Text.Clean)",
          "in",
          "    AutoRemovedColumns1"
        ]
      }
    ]
  },
  "id": "SemanticModel"
}